// Code generated by ent, DO NOT EDIT.

package document

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the document type in the database.
	Label = "document"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldYear holds the string denoting the year field in the database.
	FieldYear = "year"
	// FieldDepth1 holds the string denoting the depth1 field in the database.
	FieldDepth1 = "depth1"
	// FieldDepth2 holds the string denoting the depth2 field in the database.
	FieldDepth2 = "depth2"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedByUserID holds the string denoting the created_by_user_id field in the database.
	FieldCreatedByUserID = "created_by_user_id"
	// EdgeCreatedBy holds the string denoting the created_by edge name in mutations.
	EdgeCreatedBy = "created_by"
	// EdgeAliases holds the string denoting the aliases edge name in mutations.
	EdgeAliases = "aliases"
	// EdgeEmbedding holds the string denoting the embedding edge name in mutations.
	EdgeEmbedding = "embedding"
	// EdgeAcls holds the string denoting the acls edge name in mutations.
	EdgeAcls = "acls"
	// Table holds the table name of the document in the database.
	Table = "documents"
	// CreatedByTable is the table that holds the created_by relation/edge.
	CreatedByTable = "documents"
	// CreatedByInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatedByInverseTable = "users"
	// CreatedByColumn is the table column denoting the created_by relation/edge.
	CreatedByColumn = "created_by_user_id"
	// AliasesTable is the table that holds the aliases relation/edge.
	AliasesTable = "document_alias"
	// AliasesInverseTable is the table name for the DocumentAlias entity.
	// It exists in this package in order to avoid circular dependency with the "documentalias" package.
	AliasesInverseTable = "document_alias"
	// AliasesColumn is the table column denoting the aliases relation/edge.
	AliasesColumn = "document_id"
	// EmbeddingTable is the table that holds the embedding relation/edge.
	EmbeddingTable = "document_embeddings"
	// EmbeddingInverseTable is the table name for the DocumentEmbedding entity.
	// It exists in this package in order to avoid circular dependency with the "documentembedding" package.
	EmbeddingInverseTable = "document_embeddings"
	// EmbeddingColumn is the table column denoting the embedding relation/edge.
	EmbeddingColumn = "document_id"
	// AclsTable is the table that holds the acls relation/edge.
	AclsTable = "document_ac_ls"
	// AclsInverseTable is the table name for the DocumentACL entity.
	// It exists in this package in order to avoid circular dependency with the "documentacl" package.
	AclsInverseTable = "document_ac_ls"
	// AclsColumn is the table column denoting the acls relation/edge.
	AclsColumn = "document_id"
)

// Columns holds all SQL columns for document fields.
var Columns = []string{
	FieldID,
	FieldYear,
	FieldDepth1,
	FieldDepth2,
	FieldTitle,
	FieldContent,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCreatedByUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// Depth1Validator is a validator for the "depth1" field. It is called by the builders before save.
	Depth1Validator func(string) error
	// Depth2Validator is a validator for the "depth2" field. It is called by the builders before save.
	Depth2Validator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Document queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByYear orders the results by the year field.
func ByYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYear, opts...).ToFunc()
}

// ByDepth1 orders the results by the depth1 field.
func ByDepth1(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepth1, opts...).ToFunc()
}

// ByDepth2 orders the results by the depth2 field.
func ByDepth2(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepth2, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedByUserID orders the results by the created_by_user_id field.
func ByCreatedByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByUserID, opts...).ToFunc()
}

// ByCreatedByField orders the results by created_by field.
func ByCreatedByField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatedByStep(), sql.OrderByField(field, opts...))
	}
}

// ByAliasesCount orders the results by aliases count.
func ByAliasesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAliasesStep(), opts...)
	}
}

// ByAliases orders the results by aliases terms.
func ByAliases(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAliasesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEmbeddingField orders the results by embedding field.
func ByEmbeddingField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEmbeddingStep(), sql.OrderByField(field, opts...))
	}
}

// ByAclsCount orders the results by acls count.
func ByAclsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAclsStep(), opts...)
	}
}

// ByAcls orders the results by acls terms.
func ByAcls(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAclsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCreatedByStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatedByInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatedByTable, CreatedByColumn),
	)
}
func newAliasesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AliasesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AliasesTable, AliasesColumn),
	)
}
func newEmbeddingStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EmbeddingInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, EmbeddingTable, EmbeddingColumn),
	)
}
func newAclsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AclsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AclsTable, AclsColumn),
	)
}
