// Code generated by ent, DO NOT EDIT.

package document

import (
	"document-mdp/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldID, id))
}

// Year applies equality check predicate on the "year" field. It's identical to YearEQ.
func Year(v int) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldYear, v))
}

// Depth1 applies equality check predicate on the "depth1" field. It's identical to Depth1EQ.
func Depth1(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDepth1, v))
}

// Depth2 applies equality check predicate on the "depth2" field. It's identical to Depth2EQ.
func Depth2(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDepth2, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldTitle, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldContent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedByUserID applies equality check predicate on the "created_by_user_id" field. It's identical to CreatedByUserIDEQ.
func CreatedByUserID(v uuid.UUID) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldCreatedByUserID, v))
}

// YearEQ applies the EQ predicate on the "year" field.
func YearEQ(v int) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldYear, v))
}

// YearNEQ applies the NEQ predicate on the "year" field.
func YearNEQ(v int) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldYear, v))
}

// YearIn applies the In predicate on the "year" field.
func YearIn(vs ...int) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldYear, vs...))
}

// YearNotIn applies the NotIn predicate on the "year" field.
func YearNotIn(vs ...int) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldYear, vs...))
}

// YearGT applies the GT predicate on the "year" field.
func YearGT(v int) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldYear, v))
}

// YearGTE applies the GTE predicate on the "year" field.
func YearGTE(v int) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldYear, v))
}

// YearLT applies the LT predicate on the "year" field.
func YearLT(v int) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldYear, v))
}

// YearLTE applies the LTE predicate on the "year" field.
func YearLTE(v int) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldYear, v))
}

// Depth1EQ applies the EQ predicate on the "depth1" field.
func Depth1EQ(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDepth1, v))
}

// Depth1NEQ applies the NEQ predicate on the "depth1" field.
func Depth1NEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldDepth1, v))
}

// Depth1In applies the In predicate on the "depth1" field.
func Depth1In(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldDepth1, vs...))
}

// Depth1NotIn applies the NotIn predicate on the "depth1" field.
func Depth1NotIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldDepth1, vs...))
}

// Depth1GT applies the GT predicate on the "depth1" field.
func Depth1GT(v string) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldDepth1, v))
}

// Depth1GTE applies the GTE predicate on the "depth1" field.
func Depth1GTE(v string) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldDepth1, v))
}

// Depth1LT applies the LT predicate on the "depth1" field.
func Depth1LT(v string) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldDepth1, v))
}

// Depth1LTE applies the LTE predicate on the "depth1" field.
func Depth1LTE(v string) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldDepth1, v))
}

// Depth1Contains applies the Contains predicate on the "depth1" field.
func Depth1Contains(v string) predicate.Document {
	return predicate.Document(sql.FieldContains(FieldDepth1, v))
}

// Depth1HasPrefix applies the HasPrefix predicate on the "depth1" field.
func Depth1HasPrefix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasPrefix(FieldDepth1, v))
}

// Depth1HasSuffix applies the HasSuffix predicate on the "depth1" field.
func Depth1HasSuffix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasSuffix(FieldDepth1, v))
}

// Depth1EqualFold applies the EqualFold predicate on the "depth1" field.
func Depth1EqualFold(v string) predicate.Document {
	return predicate.Document(sql.FieldEqualFold(FieldDepth1, v))
}

// Depth1ContainsFold applies the ContainsFold predicate on the "depth1" field.
func Depth1ContainsFold(v string) predicate.Document {
	return predicate.Document(sql.FieldContainsFold(FieldDepth1, v))
}

// Depth2EQ applies the EQ predicate on the "depth2" field.
func Depth2EQ(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDepth2, v))
}

// Depth2NEQ applies the NEQ predicate on the "depth2" field.
func Depth2NEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldDepth2, v))
}

// Depth2In applies the In predicate on the "depth2" field.
func Depth2In(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldDepth2, vs...))
}

// Depth2NotIn applies the NotIn predicate on the "depth2" field.
func Depth2NotIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldDepth2, vs...))
}

// Depth2GT applies the GT predicate on the "depth2" field.
func Depth2GT(v string) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldDepth2, v))
}

// Depth2GTE applies the GTE predicate on the "depth2" field.
func Depth2GTE(v string) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldDepth2, v))
}

// Depth2LT applies the LT predicate on the "depth2" field.
func Depth2LT(v string) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldDepth2, v))
}

// Depth2LTE applies the LTE predicate on the "depth2" field.
func Depth2LTE(v string) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldDepth2, v))
}

// Depth2Contains applies the Contains predicate on the "depth2" field.
func Depth2Contains(v string) predicate.Document {
	return predicate.Document(sql.FieldContains(FieldDepth2, v))
}

// Depth2HasPrefix applies the HasPrefix predicate on the "depth2" field.
func Depth2HasPrefix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasPrefix(FieldDepth2, v))
}

// Depth2HasSuffix applies the HasSuffix predicate on the "depth2" field.
func Depth2HasSuffix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasSuffix(FieldDepth2, v))
}

// Depth2EqualFold applies the EqualFold predicate on the "depth2" field.
func Depth2EqualFold(v string) predicate.Document {
	return predicate.Document(sql.FieldEqualFold(FieldDepth2, v))
}

// Depth2ContainsFold applies the ContainsFold predicate on the "depth2" field.
func Depth2ContainsFold(v string) predicate.Document {
	return predicate.Document(sql.FieldContainsFold(FieldDepth2, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Document {
	return predicate.Document(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Document {
	return predicate.Document(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Document {
	return predicate.Document(sql.FieldContainsFold(FieldTitle, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Document {
	return predicate.Document(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.Document {
	return predicate.Document(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.Document {
	return predicate.Document(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Document {
	return predicate.Document(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Document {
	return predicate.Document(sql.FieldContainsFold(FieldContent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByUserIDEQ applies the EQ predicate on the "created_by_user_id" field.
func CreatedByUserIDEQ(v uuid.UUID) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDNEQ applies the NEQ predicate on the "created_by_user_id" field.
func CreatedByUserIDNEQ(v uuid.UUID) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDIn applies the In predicate on the "created_by_user_id" field.
func CreatedByUserIDIn(vs ...uuid.UUID) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDNotIn applies the NotIn predicate on the "created_by_user_id" field.
func CreatedByUserIDNotIn(vs ...uuid.UUID) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldCreatedByUserID, vs...))
}

// HasCreatedBy applies the HasEdge predicate on the "created_by" edge.
func HasCreatedBy() predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatedByTable, CreatedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatedByWith applies the HasEdge predicate on the "created_by" edge with a given conditions (other predicates).
func HasCreatedByWith(preds ...predicate.User) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		step := newCreatedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAliases applies the HasEdge predicate on the "aliases" edge.
func HasAliases() predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AliasesTable, AliasesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAliasesWith applies the HasEdge predicate on the "aliases" edge with a given conditions (other predicates).
func HasAliasesWith(preds ...predicate.DocumentAlias) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		step := newAliasesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEmbedding applies the HasEdge predicate on the "embedding" edge.
func HasEmbedding() predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, EmbeddingTable, EmbeddingColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEmbeddingWith applies the HasEdge predicate on the "embedding" edge with a given conditions (other predicates).
func HasEmbeddingWith(preds ...predicate.DocumentEmbedding) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		step := newEmbeddingStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAcls applies the HasEdge predicate on the "acls" edge.
func HasAcls() predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AclsTable, AclsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAclsWith applies the HasEdge predicate on the "acls" edge with a given conditions (other predicates).
func HasAclsWith(preds ...predicate.DocumentACL) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		step := newAclsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Document) predicate.Document {
	return predicate.Document(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Document) predicate.Document {
	return predicate.Document(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Document) predicate.Document {
	return predicate.Document(sql.NotPredicates(p))
}
