// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DocumentsColumns holds the columns for the "documents" table.
	DocumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "year", Type: field.TypeInt},
		{Name: "depth1", Type: field.TypeString, Size: 80},
		{Name: "depth2", Type: field.TypeString, Size: 80},
		{Name: "title", Type: field.TypeString, Size: 300},
		{Name: "content", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by_user_id", Type: field.TypeUUID},
	}
	// DocumentsTable holds the schema information for the "documents" table.
	DocumentsTable = &schema.Table{
		Name:       "documents",
		Columns:    DocumentsColumns,
		PrimaryKey: []*schema.Column{DocumentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "documents_users_documents_created",
				Columns:    []*schema.Column{DocumentsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "document_year_depth1_depth2_title",
				Unique:  false,
				Columns: []*schema.Column{DocumentsColumns[1], DocumentsColumns[2], DocumentsColumns[3], DocumentsColumns[4]},
			},
			{
				Name:    "document_year",
				Unique:  false,
				Columns: []*schema.Column{DocumentsColumns[1]},
			},
			{
				Name:    "document_depth1_depth2",
				Unique:  false,
				Columns: []*schema.Column{DocumentsColumns[2], DocumentsColumns[3]},
			},
		},
	}
	// DocumentAcLsColumns holds the columns for the "document_ac_ls" table.
	DocumentAcLsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "effect", Type: field.TypeEnum, Enums: []string{"deny", "read", "read_write"}, Default: "read"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "document_id", Type: field.TypeUUID},
		{Name: "group_id", Type: field.TypeUUID},
	}
	// DocumentAcLsTable holds the schema information for the "document_ac_ls" table.
	DocumentAcLsTable = &schema.Table{
		Name:       "document_ac_ls",
		Columns:    DocumentAcLsColumns,
		PrimaryKey: []*schema.Column{DocumentAcLsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "document_ac_ls_documents_acls",
				Columns:    []*schema.Column{DocumentAcLsColumns[4]},
				RefColumns: []*schema.Column{DocumentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "document_ac_ls_groups_document_acls",
				Columns:    []*schema.Column{DocumentAcLsColumns[5]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "documentacl_document_id_group_id",
				Unique:  true,
				Columns: []*schema.Column{DocumentAcLsColumns[4], DocumentAcLsColumns[5]},
			},
			{
				Name:    "documentacl_group_id",
				Unique:  false,
				Columns: []*schema.Column{DocumentAcLsColumns[5]},
			},
		},
	}
	// DocumentAliasColumns holds the columns for the "document_alias" table.
	DocumentAliasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "alias", Type: field.TypeString, Size: 120},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "document_id", Type: field.TypeUUID},
	}
	// DocumentAliasTable holds the schema information for the "document_alias" table.
	DocumentAliasTable = &schema.Table{
		Name:       "document_alias",
		Columns:    DocumentAliasColumns,
		PrimaryKey: []*schema.Column{DocumentAliasColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "document_alias_documents_aliases",
				Columns:    []*schema.Column{DocumentAliasColumns[3]},
				RefColumns: []*schema.Column{DocumentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "documentalias_alias",
				Unique:  false,
				Columns: []*schema.Column{DocumentAliasColumns[1]},
			},
			{
				Name:    "documentalias_document_id",
				Unique:  false,
				Columns: []*schema.Column{DocumentAliasColumns[3]},
			},
			{
				Name:    "documentalias_document_id_alias",
				Unique:  true,
				Columns: []*schema.Column{DocumentAliasColumns[3], DocumentAliasColumns[1]},
			},
		},
	}
	// DocumentEmbeddingsColumns holds the columns for the "document_embeddings" table.
	DocumentEmbeddingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "model", Type: field.TypeString, Size: 100},
		{Name: "dims", Type: field.TypeInt},
		{Name: "embedding", Type: field.TypeOther, SchemaType: map[string]string{"postgres": "vector(1536)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "document_id", Type: field.TypeUUID, Unique: true},
	}
	// DocumentEmbeddingsTable holds the schema information for the "document_embeddings" table.
	DocumentEmbeddingsTable = &schema.Table{
		Name:       "document_embeddings",
		Columns:    DocumentEmbeddingsColumns,
		PrimaryKey: []*schema.Column{DocumentEmbeddingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "document_embeddings_documents_embedding",
				Columns:    []*schema.Column{DocumentEmbeddingsColumns[5]},
				RefColumns: []*schema.Column{DocumentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "documentembedding_document_id",
				Unique:  true,
				Columns: []*schema.Column{DocumentEmbeddingsColumns[5]},
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 120},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "group_name",
				Unique:  true,
				Columns: []*schema.Column{GroupsColumns[1]},
			},
		},
	}
	// RefreshTokensColumns holds the columns for the "refresh_tokens" table.
	RefreshTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "token_hash", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_agent", Type: field.TypeString, Nullable: true, Size: 300},
		{Name: "ip", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// RefreshTokensTable holds the schema information for the "refresh_tokens" table.
	RefreshTokensTable = &schema.Table{
		Name:       "refresh_tokens",
		Columns:    RefreshTokensColumns,
		PrimaryKey: []*schema.Column{RefreshTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "refresh_tokens_users_refresh_tokens",
				Columns:    []*schema.Column{RefreshTokensColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "refreshtoken_token_hash",
				Unique:  true,
				Columns: []*schema.Column{RefreshTokensColumns[1]},
			},
			{
				Name:    "refreshtoken_user_id",
				Unique:  false,
				Columns: []*schema.Column{RefreshTokensColumns[7]},
			},
			{
				Name:    "refreshtoken_expires_at",
				Unique:  false,
				Columns: []*schema.Column{RefreshTokensColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Size: 320},
		{Name: "password_hash", Type: field.TypeString, Size: 2147483647},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
		},
	}
	// UserGroupsColumns holds the columns for the "user_groups" table.
	UserGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "group_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// UserGroupsTable holds the schema information for the "user_groups" table.
	UserGroupsTable = &schema.Table{
		Name:       "user_groups",
		Columns:    UserGroupsColumns,
		PrimaryKey: []*schema.Column{UserGroupsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_groups_groups_user_groups",
				Columns:    []*schema.Column{UserGroupsColumns[2]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_groups_users_user_groups",
				Columns:    []*schema.Column{UserGroupsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usergroup_user_id_group_id",
				Unique:  true,
				Columns: []*schema.Column{UserGroupsColumns[3], UserGroupsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DocumentsTable,
		DocumentAcLsTable,
		DocumentAliasTable,
		DocumentEmbeddingsTable,
		GroupsTable,
		RefreshTokensTable,
		UsersTable,
		UserGroupsTable,
	}
)

func init() {
	DocumentsTable.ForeignKeys[0].RefTable = UsersTable
	DocumentAcLsTable.ForeignKeys[0].RefTable = DocumentsTable
	DocumentAcLsTable.ForeignKeys[1].RefTable = GroupsTable
	DocumentAliasTable.ForeignKeys[0].RefTable = DocumentsTable
	DocumentEmbeddingsTable.ForeignKeys[0].RefTable = DocumentsTable
	RefreshTokensTable.ForeignKeys[0].RefTable = UsersTable
	UserGroupsTable.ForeignKeys[0].RefTable = GroupsTable
	UserGroupsTable.ForeignKeys[1].RefTable = UsersTable
}
