// Code generated by ent, DO NOT EDIT.

package ent

import (
	"document-mdp/ent/document"
	"document-mdp/ent/documentembedding"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

// DocumentEmbedding is the model entity for the DocumentEmbedding schema.
type DocumentEmbedding struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Dims holds the value of the "dims" field.
	Dims int `json:"dims,omitempty"`
	// Embedding holds the value of the "embedding" field.
	Embedding pgvector.Vector `json:"embedding,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// DocumentID holds the value of the "document_id" field.
	DocumentID uuid.UUID `json:"document_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DocumentEmbeddingQuery when eager-loading is set.
	Edges        DocumentEmbeddingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DocumentEmbeddingEdges holds the relations/edges for other nodes in the graph.
type DocumentEmbeddingEdges struct {
	// Document holds the value of the document edge.
	Document *Document `json:"document,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DocumentOrErr returns the Document value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DocumentEmbeddingEdges) DocumentOrErr() (*Document, error) {
	if e.Document != nil {
		return e.Document, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: document.Label}
	}
	return nil, &NotLoadedError{edge: "document"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DocumentEmbedding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case documentembedding.FieldEmbedding:
			values[i] = new(pgvector.Vector)
		case documentembedding.FieldDims:
			values[i] = new(sql.NullInt64)
		case documentembedding.FieldModel:
			values[i] = new(sql.NullString)
		case documentembedding.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case documentembedding.FieldID, documentembedding.FieldDocumentID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DocumentEmbedding fields.
func (_m *DocumentEmbedding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case documentembedding.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case documentembedding.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case documentembedding.FieldDims:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field dims", values[i])
			} else if value.Valid {
				_m.Dims = int(value.Int64)
			}
		case documentembedding.FieldEmbedding:
			if value, ok := values[i].(*pgvector.Vector); !ok {
				return fmt.Errorf("unexpected type %T for field embedding", values[i])
			} else if value != nil {
				_m.Embedding = *value
			}
		case documentembedding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case documentembedding.FieldDocumentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field document_id", values[i])
			} else if value != nil {
				_m.DocumentID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DocumentEmbedding.
// This includes values selected through modifiers, order, etc.
func (_m *DocumentEmbedding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDocument queries the "document" edge of the DocumentEmbedding entity.
func (_m *DocumentEmbedding) QueryDocument() *DocumentQuery {
	return NewDocumentEmbeddingClient(_m.config).QueryDocument(_m)
}

// Update returns a builder for updating this DocumentEmbedding.
// Note that you need to call DocumentEmbedding.Unwrap() before calling this method if this DocumentEmbedding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DocumentEmbedding) Update() *DocumentEmbeddingUpdateOne {
	return NewDocumentEmbeddingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DocumentEmbedding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DocumentEmbedding) Unwrap() *DocumentEmbedding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DocumentEmbedding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DocumentEmbedding) String() string {
	var builder strings.Builder
	builder.WriteString("DocumentEmbedding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("dims=")
	builder.WriteString(fmt.Sprintf("%v", _m.Dims))
	builder.WriteString(", ")
	builder.WriteString("embedding=")
	builder.WriteString(fmt.Sprintf("%v", _m.Embedding))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("document_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DocumentID))
	builder.WriteByte(')')
	return builder.String()
}

// DocumentEmbeddings is a parsable slice of DocumentEmbedding.
type DocumentEmbeddings []*DocumentEmbedding
