// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"document-mdp/ent/document"
	"document-mdp/ent/documentembedding"
	"document-mdp/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DocumentEmbeddingQuery is the builder for querying DocumentEmbedding entities.
type DocumentEmbeddingQuery struct {
	config
	ctx          *QueryContext
	order        []documentembedding.OrderOption
	inters       []Interceptor
	predicates   []predicate.DocumentEmbedding
	withDocument *DocumentQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DocumentEmbeddingQuery builder.
func (_q *DocumentEmbeddingQuery) Where(ps ...predicate.DocumentEmbedding) *DocumentEmbeddingQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DocumentEmbeddingQuery) Limit(limit int) *DocumentEmbeddingQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DocumentEmbeddingQuery) Offset(offset int) *DocumentEmbeddingQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DocumentEmbeddingQuery) Unique(unique bool) *DocumentEmbeddingQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DocumentEmbeddingQuery) Order(o ...documentembedding.OrderOption) *DocumentEmbeddingQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDocument chains the current query on the "document" edge.
func (_q *DocumentEmbeddingQuery) QueryDocument() *DocumentQuery {
	query := (&DocumentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(documentembedding.Table, documentembedding.FieldID, selector),
			sqlgraph.To(document.Table, document.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, documentembedding.DocumentTable, documentembedding.DocumentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DocumentEmbedding entity from the query.
// Returns a *NotFoundError when no DocumentEmbedding was found.
func (_q *DocumentEmbeddingQuery) First(ctx context.Context) (*DocumentEmbedding, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{documentembedding.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DocumentEmbeddingQuery) FirstX(ctx context.Context) *DocumentEmbedding {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DocumentEmbedding ID from the query.
// Returns a *NotFoundError when no DocumentEmbedding ID was found.
func (_q *DocumentEmbeddingQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{documentembedding.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DocumentEmbeddingQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DocumentEmbedding entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DocumentEmbedding entity is found.
// Returns a *NotFoundError when no DocumentEmbedding entities are found.
func (_q *DocumentEmbeddingQuery) Only(ctx context.Context) (*DocumentEmbedding, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{documentembedding.Label}
	default:
		return nil, &NotSingularError{documentembedding.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DocumentEmbeddingQuery) OnlyX(ctx context.Context) *DocumentEmbedding {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DocumentEmbedding ID in the query.
// Returns a *NotSingularError when more than one DocumentEmbedding ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DocumentEmbeddingQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{documentembedding.Label}
	default:
		err = &NotSingularError{documentembedding.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DocumentEmbeddingQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DocumentEmbeddings.
func (_q *DocumentEmbeddingQuery) All(ctx context.Context) ([]*DocumentEmbedding, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DocumentEmbedding, *DocumentEmbeddingQuery]()
	return withInterceptors[[]*DocumentEmbedding](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DocumentEmbeddingQuery) AllX(ctx context.Context) []*DocumentEmbedding {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DocumentEmbedding IDs.
func (_q *DocumentEmbeddingQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(documentembedding.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DocumentEmbeddingQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DocumentEmbeddingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DocumentEmbeddingQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DocumentEmbeddingQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DocumentEmbeddingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DocumentEmbeddingQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DocumentEmbeddingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DocumentEmbeddingQuery) Clone() *DocumentEmbeddingQuery {
	if _q == nil {
		return nil
	}
	return &DocumentEmbeddingQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]documentembedding.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.DocumentEmbedding{}, _q.predicates...),
		withDocument: _q.withDocument.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithDocument tells the query-builder to eager-load the nodes that are connected to
// the "document" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DocumentEmbeddingQuery) WithDocument(opts ...func(*DocumentQuery)) *DocumentEmbeddingQuery {
	query := (&DocumentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDocument = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Model string `json:"model,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DocumentEmbedding.Query().
//		GroupBy(documentembedding.FieldModel).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DocumentEmbeddingQuery) GroupBy(field string, fields ...string) *DocumentEmbeddingGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DocumentEmbeddingGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = documentembedding.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Model string `json:"model,omitempty"`
//	}
//
//	client.DocumentEmbedding.Query().
//		Select(documentembedding.FieldModel).
//		Scan(ctx, &v)
func (_q *DocumentEmbeddingQuery) Select(fields ...string) *DocumentEmbeddingSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DocumentEmbeddingSelect{DocumentEmbeddingQuery: _q}
	sbuild.label = documentembedding.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DocumentEmbeddingSelect configured with the given aggregations.
func (_q *DocumentEmbeddingQuery) Aggregate(fns ...AggregateFunc) *DocumentEmbeddingSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DocumentEmbeddingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !documentembedding.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DocumentEmbeddingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DocumentEmbedding, error) {
	var (
		nodes       = []*DocumentEmbedding{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withDocument != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DocumentEmbedding).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DocumentEmbedding{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDocument; query != nil {
		if err := _q.loadDocument(ctx, query, nodes, nil,
			func(n *DocumentEmbedding, e *Document) { n.Edges.Document = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DocumentEmbeddingQuery) loadDocument(ctx context.Context, query *DocumentQuery, nodes []*DocumentEmbedding, init func(*DocumentEmbedding), assign func(*DocumentEmbedding, *Document)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*DocumentEmbedding)
	for i := range nodes {
		fk := nodes[i].DocumentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(document.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "document_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *DocumentEmbeddingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DocumentEmbeddingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(documentembedding.Table, documentembedding.Columns, sqlgraph.NewFieldSpec(documentembedding.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, documentembedding.FieldID)
		for i := range fields {
			if fields[i] != documentembedding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withDocument != nil {
			_spec.Node.AddColumnOnce(documentembedding.FieldDocumentID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DocumentEmbeddingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(documentembedding.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = documentembedding.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *DocumentEmbeddingQuery) Modify(modifiers ...func(s *sql.Selector)) *DocumentEmbeddingSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// DocumentEmbeddingGroupBy is the group-by builder for DocumentEmbedding entities.
type DocumentEmbeddingGroupBy struct {
	selector
	build *DocumentEmbeddingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DocumentEmbeddingGroupBy) Aggregate(fns ...AggregateFunc) *DocumentEmbeddingGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DocumentEmbeddingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DocumentEmbeddingQuery, *DocumentEmbeddingGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DocumentEmbeddingGroupBy) sqlScan(ctx context.Context, root *DocumentEmbeddingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DocumentEmbeddingSelect is the builder for selecting fields of DocumentEmbedding entities.
type DocumentEmbeddingSelect struct {
	*DocumentEmbeddingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DocumentEmbeddingSelect) Aggregate(fns ...AggregateFunc) *DocumentEmbeddingSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DocumentEmbeddingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DocumentEmbeddingQuery, *DocumentEmbeddingSelect](ctx, _s.DocumentEmbeddingQuery, _s, _s.inters, v)
}

func (_s *DocumentEmbeddingSelect) sqlScan(ctx context.Context, root *DocumentEmbeddingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *DocumentEmbeddingSelect) Modify(modifiers ...func(s *sql.Selector)) *DocumentEmbeddingSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
