// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"document-mdp/ent/document"
	"document-mdp/ent/documentalias"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DocumentAliasCreate is the builder for creating a DocumentAlias entity.
type DocumentAliasCreate struct {
	config
	mutation *DocumentAliasMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAlias sets the "alias" field.
func (_c *DocumentAliasCreate) SetAlias(v string) *DocumentAliasCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DocumentAliasCreate) SetCreatedAt(v time.Time) *DocumentAliasCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DocumentAliasCreate) SetNillableCreatedAt(v *time.Time) *DocumentAliasCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetDocumentID sets the "document_id" field.
func (_c *DocumentAliasCreate) SetDocumentID(v uuid.UUID) *DocumentAliasCreate {
	_c.mutation.SetDocumentID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DocumentAliasCreate) SetID(v uuid.UUID) *DocumentAliasCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DocumentAliasCreate) SetNillableID(v *uuid.UUID) *DocumentAliasCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetDocument sets the "document" edge to the Document entity.
func (_c *DocumentAliasCreate) SetDocument(v *Document) *DocumentAliasCreate {
	return _c.SetDocumentID(v.ID)
}

// Mutation returns the DocumentAliasMutation object of the builder.
func (_c *DocumentAliasCreate) Mutation() *DocumentAliasMutation {
	return _c.mutation
}

// Save creates the DocumentAlias in the database.
func (_c *DocumentAliasCreate) Save(ctx context.Context) (*DocumentAlias, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DocumentAliasCreate) SaveX(ctx context.Context) *DocumentAlias {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentAliasCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentAliasCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DocumentAliasCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := documentalias.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := documentalias.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DocumentAliasCreate) check() error {
	if _, ok := _c.mutation.Alias(); !ok {
		return &ValidationError{Name: "alias", err: errors.New(`ent: missing required field "DocumentAlias.alias"`)}
	}
	if v, ok := _c.mutation.Alias(); ok {
		if err := documentalias.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "DocumentAlias.alias": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DocumentAlias.created_at"`)}
	}
	if _, ok := _c.mutation.DocumentID(); !ok {
		return &ValidationError{Name: "document_id", err: errors.New(`ent: missing required field "DocumentAlias.document_id"`)}
	}
	if len(_c.mutation.DocumentIDs()) == 0 {
		return &ValidationError{Name: "document", err: errors.New(`ent: missing required edge "DocumentAlias.document"`)}
	}
	return nil
}

func (_c *DocumentAliasCreate) sqlSave(ctx context.Context) (*DocumentAlias, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DocumentAliasCreate) createSpec() (*DocumentAlias, *sqlgraph.CreateSpec) {
	var (
		_node = &DocumentAlias{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(documentalias.Table, sqlgraph.NewFieldSpec(documentalias.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(documentalias.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(documentalias.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentalias.DocumentTable,
			Columns: []string{documentalias.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DocumentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DocumentAlias.Create().
//		SetAlias(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DocumentAliasUpsert) {
//			SetAlias(v+v).
//		}).
//		Exec(ctx)
func (_c *DocumentAliasCreate) OnConflict(opts ...sql.ConflictOption) *DocumentAliasUpsertOne {
	_c.conflict = opts
	return &DocumentAliasUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DocumentAlias.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DocumentAliasCreate) OnConflictColumns(columns ...string) *DocumentAliasUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DocumentAliasUpsertOne{
		create: _c,
	}
}

type (
	// DocumentAliasUpsertOne is the builder for "upsert"-ing
	//  one DocumentAlias node.
	DocumentAliasUpsertOne struct {
		create *DocumentAliasCreate
	}

	// DocumentAliasUpsert is the "OnConflict" setter.
	DocumentAliasUpsert struct {
		*sql.UpdateSet
	}
)

// SetAlias sets the "alias" field.
func (u *DocumentAliasUpsert) SetAlias(v string) *DocumentAliasUpsert {
	u.Set(documentalias.FieldAlias, v)
	return u
}

// UpdateAlias sets the "alias" field to the value that was provided on create.
func (u *DocumentAliasUpsert) UpdateAlias() *DocumentAliasUpsert {
	u.SetExcluded(documentalias.FieldAlias)
	return u
}

// SetDocumentID sets the "document_id" field.
func (u *DocumentAliasUpsert) SetDocumentID(v uuid.UUID) *DocumentAliasUpsert {
	u.Set(documentalias.FieldDocumentID, v)
	return u
}

// UpdateDocumentID sets the "document_id" field to the value that was provided on create.
func (u *DocumentAliasUpsert) UpdateDocumentID() *DocumentAliasUpsert {
	u.SetExcluded(documentalias.FieldDocumentID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DocumentAlias.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(documentalias.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DocumentAliasUpsertOne) UpdateNewValues() *DocumentAliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(documentalias.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(documentalias.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DocumentAlias.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DocumentAliasUpsertOne) Ignore() *DocumentAliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DocumentAliasUpsertOne) DoNothing() *DocumentAliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DocumentAliasCreate.OnConflict
// documentation for more info.
func (u *DocumentAliasUpsertOne) Update(set func(*DocumentAliasUpsert)) *DocumentAliasUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DocumentAliasUpsert{UpdateSet: update})
	}))
	return u
}

// SetAlias sets the "alias" field.
func (u *DocumentAliasUpsertOne) SetAlias(v string) *DocumentAliasUpsertOne {
	return u.Update(func(s *DocumentAliasUpsert) {
		s.SetAlias(v)
	})
}

// UpdateAlias sets the "alias" field to the value that was provided on create.
func (u *DocumentAliasUpsertOne) UpdateAlias() *DocumentAliasUpsertOne {
	return u.Update(func(s *DocumentAliasUpsert) {
		s.UpdateAlias()
	})
}

// SetDocumentID sets the "document_id" field.
func (u *DocumentAliasUpsertOne) SetDocumentID(v uuid.UUID) *DocumentAliasUpsertOne {
	return u.Update(func(s *DocumentAliasUpsert) {
		s.SetDocumentID(v)
	})
}

// UpdateDocumentID sets the "document_id" field to the value that was provided on create.
func (u *DocumentAliasUpsertOne) UpdateDocumentID() *DocumentAliasUpsertOne {
	return u.Update(func(s *DocumentAliasUpsert) {
		s.UpdateDocumentID()
	})
}

// Exec executes the query.
func (u *DocumentAliasUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DocumentAliasCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DocumentAliasUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DocumentAliasUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DocumentAliasUpsertOne.ID is not supported by MySQL driver. Use DocumentAliasUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DocumentAliasUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DocumentAliasCreateBulk is the builder for creating many DocumentAlias entities in bulk.
type DocumentAliasCreateBulk struct {
	config
	err      error
	builders []*DocumentAliasCreate
	conflict []sql.ConflictOption
}

// Save creates the DocumentAlias entities in the database.
func (_c *DocumentAliasCreateBulk) Save(ctx context.Context) ([]*DocumentAlias, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DocumentAlias, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DocumentAliasMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DocumentAliasCreateBulk) SaveX(ctx context.Context) []*DocumentAlias {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentAliasCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentAliasCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DocumentAlias.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DocumentAliasUpsert) {
//			SetAlias(v+v).
//		}).
//		Exec(ctx)
func (_c *DocumentAliasCreateBulk) OnConflict(opts ...sql.ConflictOption) *DocumentAliasUpsertBulk {
	_c.conflict = opts
	return &DocumentAliasUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DocumentAlias.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DocumentAliasCreateBulk) OnConflictColumns(columns ...string) *DocumentAliasUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DocumentAliasUpsertBulk{
		create: _c,
	}
}

// DocumentAliasUpsertBulk is the builder for "upsert"-ing
// a bulk of DocumentAlias nodes.
type DocumentAliasUpsertBulk struct {
	create *DocumentAliasCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DocumentAlias.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(documentalias.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DocumentAliasUpsertBulk) UpdateNewValues() *DocumentAliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(documentalias.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(documentalias.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DocumentAlias.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DocumentAliasUpsertBulk) Ignore() *DocumentAliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DocumentAliasUpsertBulk) DoNothing() *DocumentAliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DocumentAliasCreateBulk.OnConflict
// documentation for more info.
func (u *DocumentAliasUpsertBulk) Update(set func(*DocumentAliasUpsert)) *DocumentAliasUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DocumentAliasUpsert{UpdateSet: update})
	}))
	return u
}

// SetAlias sets the "alias" field.
func (u *DocumentAliasUpsertBulk) SetAlias(v string) *DocumentAliasUpsertBulk {
	return u.Update(func(s *DocumentAliasUpsert) {
		s.SetAlias(v)
	})
}

// UpdateAlias sets the "alias" field to the value that was provided on create.
func (u *DocumentAliasUpsertBulk) UpdateAlias() *DocumentAliasUpsertBulk {
	return u.Update(func(s *DocumentAliasUpsert) {
		s.UpdateAlias()
	})
}

// SetDocumentID sets the "document_id" field.
func (u *DocumentAliasUpsertBulk) SetDocumentID(v uuid.UUID) *DocumentAliasUpsertBulk {
	return u.Update(func(s *DocumentAliasUpsert) {
		s.SetDocumentID(v)
	})
}

// UpdateDocumentID sets the "document_id" field to the value that was provided on create.
func (u *DocumentAliasUpsertBulk) UpdateDocumentID() *DocumentAliasUpsertBulk {
	return u.Update(func(s *DocumentAliasUpsert) {
		s.UpdateDocumentID()
	})
}

// Exec executes the query.
func (u *DocumentAliasUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DocumentAliasCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DocumentAliasCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DocumentAliasUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
