// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"document-mdp/ent/document"
	"document-mdp/ent/documentembedding"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

// DocumentEmbeddingCreate is the builder for creating a DocumentEmbedding entity.
type DocumentEmbeddingCreate struct {
	config
	mutation *DocumentEmbeddingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetModel sets the "model" field.
func (_c *DocumentEmbeddingCreate) SetModel(v string) *DocumentEmbeddingCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetDims sets the "dims" field.
func (_c *DocumentEmbeddingCreate) SetDims(v int) *DocumentEmbeddingCreate {
	_c.mutation.SetDims(v)
	return _c
}

// SetEmbedding sets the "embedding" field.
func (_c *DocumentEmbeddingCreate) SetEmbedding(v pgvector.Vector) *DocumentEmbeddingCreate {
	_c.mutation.SetEmbedding(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DocumentEmbeddingCreate) SetCreatedAt(v time.Time) *DocumentEmbeddingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DocumentEmbeddingCreate) SetNillableCreatedAt(v *time.Time) *DocumentEmbeddingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetDocumentID sets the "document_id" field.
func (_c *DocumentEmbeddingCreate) SetDocumentID(v uuid.UUID) *DocumentEmbeddingCreate {
	_c.mutation.SetDocumentID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DocumentEmbeddingCreate) SetID(v uuid.UUID) *DocumentEmbeddingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DocumentEmbeddingCreate) SetNillableID(v *uuid.UUID) *DocumentEmbeddingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetDocument sets the "document" edge to the Document entity.
func (_c *DocumentEmbeddingCreate) SetDocument(v *Document) *DocumentEmbeddingCreate {
	return _c.SetDocumentID(v.ID)
}

// Mutation returns the DocumentEmbeddingMutation object of the builder.
func (_c *DocumentEmbeddingCreate) Mutation() *DocumentEmbeddingMutation {
	return _c.mutation
}

// Save creates the DocumentEmbedding in the database.
func (_c *DocumentEmbeddingCreate) Save(ctx context.Context) (*DocumentEmbedding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DocumentEmbeddingCreate) SaveX(ctx context.Context) *DocumentEmbedding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentEmbeddingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentEmbeddingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DocumentEmbeddingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := documentembedding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := documentembedding.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DocumentEmbeddingCreate) check() error {
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "DocumentEmbedding.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := documentembedding.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "DocumentEmbedding.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Dims(); !ok {
		return &ValidationError{Name: "dims", err: errors.New(`ent: missing required field "DocumentEmbedding.dims"`)}
	}
	if _, ok := _c.mutation.Embedding(); !ok {
		return &ValidationError{Name: "embedding", err: errors.New(`ent: missing required field "DocumentEmbedding.embedding"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DocumentEmbedding.created_at"`)}
	}
	if _, ok := _c.mutation.DocumentID(); !ok {
		return &ValidationError{Name: "document_id", err: errors.New(`ent: missing required field "DocumentEmbedding.document_id"`)}
	}
	if len(_c.mutation.DocumentIDs()) == 0 {
		return &ValidationError{Name: "document", err: errors.New(`ent: missing required edge "DocumentEmbedding.document"`)}
	}
	return nil
}

func (_c *DocumentEmbeddingCreate) sqlSave(ctx context.Context) (*DocumentEmbedding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DocumentEmbeddingCreate) createSpec() (*DocumentEmbedding, *sqlgraph.CreateSpec) {
	var (
		_node = &DocumentEmbedding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(documentembedding.Table, sqlgraph.NewFieldSpec(documentembedding.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(documentembedding.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Dims(); ok {
		_spec.SetField(documentembedding.FieldDims, field.TypeInt, value)
		_node.Dims = value
	}
	if value, ok := _c.mutation.Embedding(); ok {
		_spec.SetField(documentembedding.FieldEmbedding, field.TypeOther, value)
		_node.Embedding = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(documentembedding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   documentembedding.DocumentTable,
			Columns: []string{documentembedding.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DocumentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DocumentEmbedding.Create().
//		SetModel(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DocumentEmbeddingUpsert) {
//			SetModel(v+v).
//		}).
//		Exec(ctx)
func (_c *DocumentEmbeddingCreate) OnConflict(opts ...sql.ConflictOption) *DocumentEmbeddingUpsertOne {
	_c.conflict = opts
	return &DocumentEmbeddingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DocumentEmbedding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DocumentEmbeddingCreate) OnConflictColumns(columns ...string) *DocumentEmbeddingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DocumentEmbeddingUpsertOne{
		create: _c,
	}
}

type (
	// DocumentEmbeddingUpsertOne is the builder for "upsert"-ing
	//  one DocumentEmbedding node.
	DocumentEmbeddingUpsertOne struct {
		create *DocumentEmbeddingCreate
	}

	// DocumentEmbeddingUpsert is the "OnConflict" setter.
	DocumentEmbeddingUpsert struct {
		*sql.UpdateSet
	}
)

// SetModel sets the "model" field.
func (u *DocumentEmbeddingUpsert) SetModel(v string) *DocumentEmbeddingUpsert {
	u.Set(documentembedding.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *DocumentEmbeddingUpsert) UpdateModel() *DocumentEmbeddingUpsert {
	u.SetExcluded(documentembedding.FieldModel)
	return u
}

// SetDims sets the "dims" field.
func (u *DocumentEmbeddingUpsert) SetDims(v int) *DocumentEmbeddingUpsert {
	u.Set(documentembedding.FieldDims, v)
	return u
}

// UpdateDims sets the "dims" field to the value that was provided on create.
func (u *DocumentEmbeddingUpsert) UpdateDims() *DocumentEmbeddingUpsert {
	u.SetExcluded(documentembedding.FieldDims)
	return u
}

// AddDims adds v to the "dims" field.
func (u *DocumentEmbeddingUpsert) AddDims(v int) *DocumentEmbeddingUpsert {
	u.Add(documentembedding.FieldDims, v)
	return u
}

// SetEmbedding sets the "embedding" field.
func (u *DocumentEmbeddingUpsert) SetEmbedding(v pgvector.Vector) *DocumentEmbeddingUpsert {
	u.Set(documentembedding.FieldEmbedding, v)
	return u
}

// UpdateEmbedding sets the "embedding" field to the value that was provided on create.
func (u *DocumentEmbeddingUpsert) UpdateEmbedding() *DocumentEmbeddingUpsert {
	u.SetExcluded(documentembedding.FieldEmbedding)
	return u
}

// SetDocumentID sets the "document_id" field.
func (u *DocumentEmbeddingUpsert) SetDocumentID(v uuid.UUID) *DocumentEmbeddingUpsert {
	u.Set(documentembedding.FieldDocumentID, v)
	return u
}

// UpdateDocumentID sets the "document_id" field to the value that was provided on create.
func (u *DocumentEmbeddingUpsert) UpdateDocumentID() *DocumentEmbeddingUpsert {
	u.SetExcluded(documentembedding.FieldDocumentID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DocumentEmbedding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(documentembedding.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DocumentEmbeddingUpsertOne) UpdateNewValues() *DocumentEmbeddingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(documentembedding.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(documentembedding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DocumentEmbedding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DocumentEmbeddingUpsertOne) Ignore() *DocumentEmbeddingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DocumentEmbeddingUpsertOne) DoNothing() *DocumentEmbeddingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DocumentEmbeddingCreate.OnConflict
// documentation for more info.
func (u *DocumentEmbeddingUpsertOne) Update(set func(*DocumentEmbeddingUpsert)) *DocumentEmbeddingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DocumentEmbeddingUpsert{UpdateSet: update})
	}))
	return u
}

// SetModel sets the "model" field.
func (u *DocumentEmbeddingUpsertOne) SetModel(v string) *DocumentEmbeddingUpsertOne {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *DocumentEmbeddingUpsertOne) UpdateModel() *DocumentEmbeddingUpsertOne {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.UpdateModel()
	})
}

// SetDims sets the "dims" field.
func (u *DocumentEmbeddingUpsertOne) SetDims(v int) *DocumentEmbeddingUpsertOne {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.SetDims(v)
	})
}

// AddDims adds v to the "dims" field.
func (u *DocumentEmbeddingUpsertOne) AddDims(v int) *DocumentEmbeddingUpsertOne {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.AddDims(v)
	})
}

// UpdateDims sets the "dims" field to the value that was provided on create.
func (u *DocumentEmbeddingUpsertOne) UpdateDims() *DocumentEmbeddingUpsertOne {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.UpdateDims()
	})
}

// SetEmbedding sets the "embedding" field.
func (u *DocumentEmbeddingUpsertOne) SetEmbedding(v pgvector.Vector) *DocumentEmbeddingUpsertOne {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.SetEmbedding(v)
	})
}

// UpdateEmbedding sets the "embedding" field to the value that was provided on create.
func (u *DocumentEmbeddingUpsertOne) UpdateEmbedding() *DocumentEmbeddingUpsertOne {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.UpdateEmbedding()
	})
}

// SetDocumentID sets the "document_id" field.
func (u *DocumentEmbeddingUpsertOne) SetDocumentID(v uuid.UUID) *DocumentEmbeddingUpsertOne {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.SetDocumentID(v)
	})
}

// UpdateDocumentID sets the "document_id" field to the value that was provided on create.
func (u *DocumentEmbeddingUpsertOne) UpdateDocumentID() *DocumentEmbeddingUpsertOne {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.UpdateDocumentID()
	})
}

// Exec executes the query.
func (u *DocumentEmbeddingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DocumentEmbeddingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DocumentEmbeddingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DocumentEmbeddingUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DocumentEmbeddingUpsertOne.ID is not supported by MySQL driver. Use DocumentEmbeddingUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DocumentEmbeddingUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DocumentEmbeddingCreateBulk is the builder for creating many DocumentEmbedding entities in bulk.
type DocumentEmbeddingCreateBulk struct {
	config
	err      error
	builders []*DocumentEmbeddingCreate
	conflict []sql.ConflictOption
}

// Save creates the DocumentEmbedding entities in the database.
func (_c *DocumentEmbeddingCreateBulk) Save(ctx context.Context) ([]*DocumentEmbedding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DocumentEmbedding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DocumentEmbeddingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DocumentEmbeddingCreateBulk) SaveX(ctx context.Context) []*DocumentEmbedding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentEmbeddingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentEmbeddingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DocumentEmbedding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DocumentEmbeddingUpsert) {
//			SetModel(v+v).
//		}).
//		Exec(ctx)
func (_c *DocumentEmbeddingCreateBulk) OnConflict(opts ...sql.ConflictOption) *DocumentEmbeddingUpsertBulk {
	_c.conflict = opts
	return &DocumentEmbeddingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DocumentEmbedding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DocumentEmbeddingCreateBulk) OnConflictColumns(columns ...string) *DocumentEmbeddingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DocumentEmbeddingUpsertBulk{
		create: _c,
	}
}

// DocumentEmbeddingUpsertBulk is the builder for "upsert"-ing
// a bulk of DocumentEmbedding nodes.
type DocumentEmbeddingUpsertBulk struct {
	create *DocumentEmbeddingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DocumentEmbedding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(documentembedding.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DocumentEmbeddingUpsertBulk) UpdateNewValues() *DocumentEmbeddingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(documentembedding.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(documentembedding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DocumentEmbedding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DocumentEmbeddingUpsertBulk) Ignore() *DocumentEmbeddingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DocumentEmbeddingUpsertBulk) DoNothing() *DocumentEmbeddingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DocumentEmbeddingCreateBulk.OnConflict
// documentation for more info.
func (u *DocumentEmbeddingUpsertBulk) Update(set func(*DocumentEmbeddingUpsert)) *DocumentEmbeddingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DocumentEmbeddingUpsert{UpdateSet: update})
	}))
	return u
}

// SetModel sets the "model" field.
func (u *DocumentEmbeddingUpsertBulk) SetModel(v string) *DocumentEmbeddingUpsertBulk {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *DocumentEmbeddingUpsertBulk) UpdateModel() *DocumentEmbeddingUpsertBulk {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.UpdateModel()
	})
}

// SetDims sets the "dims" field.
func (u *DocumentEmbeddingUpsertBulk) SetDims(v int) *DocumentEmbeddingUpsertBulk {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.SetDims(v)
	})
}

// AddDims adds v to the "dims" field.
func (u *DocumentEmbeddingUpsertBulk) AddDims(v int) *DocumentEmbeddingUpsertBulk {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.AddDims(v)
	})
}

// UpdateDims sets the "dims" field to the value that was provided on create.
func (u *DocumentEmbeddingUpsertBulk) UpdateDims() *DocumentEmbeddingUpsertBulk {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.UpdateDims()
	})
}

// SetEmbedding sets the "embedding" field.
func (u *DocumentEmbeddingUpsertBulk) SetEmbedding(v pgvector.Vector) *DocumentEmbeddingUpsertBulk {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.SetEmbedding(v)
	})
}

// UpdateEmbedding sets the "embedding" field to the value that was provided on create.
func (u *DocumentEmbeddingUpsertBulk) UpdateEmbedding() *DocumentEmbeddingUpsertBulk {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.UpdateEmbedding()
	})
}

// SetDocumentID sets the "document_id" field.
func (u *DocumentEmbeddingUpsertBulk) SetDocumentID(v uuid.UUID) *DocumentEmbeddingUpsertBulk {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.SetDocumentID(v)
	})
}

// UpdateDocumentID sets the "document_id" field to the value that was provided on create.
func (u *DocumentEmbeddingUpsertBulk) UpdateDocumentID() *DocumentEmbeddingUpsertBulk {
	return u.Update(func(s *DocumentEmbeddingUpsert) {
		s.UpdateDocumentID()
	})
}

// Exec executes the query.
func (u *DocumentEmbeddingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DocumentEmbeddingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DocumentEmbeddingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DocumentEmbeddingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
