// Code generated by ent, DO NOT EDIT.

package ent

import (
	"document-mdp/ent/document"
	"document-mdp/ent/documentalias"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// DocumentAlias is the model entity for the DocumentAlias schema.
type DocumentAlias struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Alias holds the value of the "alias" field.
	Alias string `json:"alias,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// DocumentID holds the value of the "document_id" field.
	DocumentID uuid.UUID `json:"document_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DocumentAliasQuery when eager-loading is set.
	Edges        DocumentAliasEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DocumentAliasEdges holds the relations/edges for other nodes in the graph.
type DocumentAliasEdges struct {
	// Document holds the value of the document edge.
	Document *Document `json:"document,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DocumentOrErr returns the Document value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DocumentAliasEdges) DocumentOrErr() (*Document, error) {
	if e.Document != nil {
		return e.Document, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: document.Label}
	}
	return nil, &NotLoadedError{edge: "document"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DocumentAlias) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case documentalias.FieldAlias:
			values[i] = new(sql.NullString)
		case documentalias.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case documentalias.FieldID, documentalias.FieldDocumentID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DocumentAlias fields.
func (_m *DocumentAlias) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case documentalias.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case documentalias.FieldAlias:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alias", values[i])
			} else if value.Valid {
				_m.Alias = value.String
			}
		case documentalias.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case documentalias.FieldDocumentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field document_id", values[i])
			} else if value != nil {
				_m.DocumentID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DocumentAlias.
// This includes values selected through modifiers, order, etc.
func (_m *DocumentAlias) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDocument queries the "document" edge of the DocumentAlias entity.
func (_m *DocumentAlias) QueryDocument() *DocumentQuery {
	return NewDocumentAliasClient(_m.config).QueryDocument(_m)
}

// Update returns a builder for updating this DocumentAlias.
// Note that you need to call DocumentAlias.Unwrap() before calling this method if this DocumentAlias
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DocumentAlias) Update() *DocumentAliasUpdateOne {
	return NewDocumentAliasClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DocumentAlias entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DocumentAlias) Unwrap() *DocumentAlias {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DocumentAlias is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DocumentAlias) String() string {
	var builder strings.Builder
	builder.WriteString("DocumentAlias(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("alias=")
	builder.WriteString(_m.Alias)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("document_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DocumentID))
	builder.WriteByte(')')
	return builder.String()
}

// DocumentAliasSlice is a parsable slice of DocumentAlias.
type DocumentAliasSlice []*DocumentAlias
