// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"document-mdp/ent/document"
	"document-mdp/ent/documentacl"
	"document-mdp/ent/group"
	"document-mdp/ent/predicate"
	"document-mdp/ent/schema"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DocumentACLUpdate is the builder for updating DocumentACL entities.
type DocumentACLUpdate struct {
	config
	hooks     []Hook
	mutation  *DocumentACLMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DocumentACLUpdate builder.
func (_u *DocumentACLUpdate) Where(ps ...predicate.DocumentACL) *DocumentACLUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDocumentID sets the "document_id" field.
func (_u *DocumentACLUpdate) SetDocumentID(v uuid.UUID) *DocumentACLUpdate {
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *DocumentACLUpdate) SetNillableDocumentID(v *uuid.UUID) *DocumentACLUpdate {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *DocumentACLUpdate) SetGroupID(v uuid.UUID) *DocumentACLUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *DocumentACLUpdate) SetNillableGroupID(v *uuid.UUID) *DocumentACLUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetEffect sets the "effect" field.
func (_u *DocumentACLUpdate) SetEffect(v schema.ACLEffect) *DocumentACLUpdate {
	_u.mutation.SetEffect(v)
	return _u
}

// SetNillableEffect sets the "effect" field if the given value is not nil.
func (_u *DocumentACLUpdate) SetNillableEffect(v *schema.ACLEffect) *DocumentACLUpdate {
	if v != nil {
		_u.SetEffect(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DocumentACLUpdate) SetUpdatedAt(v time.Time) *DocumentACLUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDocument sets the "document" edge to the Document entity.
func (_u *DocumentACLUpdate) SetDocument(v *Document) *DocumentACLUpdate {
	return _u.SetDocumentID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *DocumentACLUpdate) SetGroup(v *Group) *DocumentACLUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the DocumentACLMutation object of the builder.
func (_u *DocumentACLUpdate) Mutation() *DocumentACLMutation {
	return _u.mutation
}

// ClearDocument clears the "document" edge to the Document entity.
func (_u *DocumentACLUpdate) ClearDocument() *DocumentACLUpdate {
	_u.mutation.ClearDocument()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *DocumentACLUpdate) ClearGroup() *DocumentACLUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DocumentACLUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentACLUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DocumentACLUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentACLUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DocumentACLUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := documentacl.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentACLUpdate) check() error {
	if v, ok := _u.mutation.Effect(); ok {
		if err := documentacl.EffectValidator(v); err != nil {
			return &ValidationError{Name: "effect", err: fmt.Errorf(`ent: validator failed for field "DocumentACL.effect": %w`, err)}
		}
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentACL.document"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentACL.group"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DocumentACLUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DocumentACLUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DocumentACLUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documentacl.Table, documentacl.Columns, sqlgraph.NewFieldSpec(documentacl.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Effect(); ok {
		_spec.SetField(documentacl.FieldEffect, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(documentacl.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentacl.DocumentTable,
			Columns: []string{documentacl.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentacl.DocumentTable,
			Columns: []string{documentacl.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentacl.GroupTable,
			Columns: []string{documentacl.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentacl.GroupTable,
			Columns: []string{documentacl.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documentacl.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DocumentACLUpdateOne is the builder for updating a single DocumentACL entity.
type DocumentACLUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DocumentACLMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDocumentID sets the "document_id" field.
func (_u *DocumentACLUpdateOne) SetDocumentID(v uuid.UUID) *DocumentACLUpdateOne {
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *DocumentACLUpdateOne) SetNillableDocumentID(v *uuid.UUID) *DocumentACLUpdateOne {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *DocumentACLUpdateOne) SetGroupID(v uuid.UUID) *DocumentACLUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *DocumentACLUpdateOne) SetNillableGroupID(v *uuid.UUID) *DocumentACLUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetEffect sets the "effect" field.
func (_u *DocumentACLUpdateOne) SetEffect(v schema.ACLEffect) *DocumentACLUpdateOne {
	_u.mutation.SetEffect(v)
	return _u
}

// SetNillableEffect sets the "effect" field if the given value is not nil.
func (_u *DocumentACLUpdateOne) SetNillableEffect(v *schema.ACLEffect) *DocumentACLUpdateOne {
	if v != nil {
		_u.SetEffect(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DocumentACLUpdateOne) SetUpdatedAt(v time.Time) *DocumentACLUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDocument sets the "document" edge to the Document entity.
func (_u *DocumentACLUpdateOne) SetDocument(v *Document) *DocumentACLUpdateOne {
	return _u.SetDocumentID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *DocumentACLUpdateOne) SetGroup(v *Group) *DocumentACLUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the DocumentACLMutation object of the builder.
func (_u *DocumentACLUpdateOne) Mutation() *DocumentACLMutation {
	return _u.mutation
}

// ClearDocument clears the "document" edge to the Document entity.
func (_u *DocumentACLUpdateOne) ClearDocument() *DocumentACLUpdateOne {
	_u.mutation.ClearDocument()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *DocumentACLUpdateOne) ClearGroup() *DocumentACLUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the DocumentACLUpdate builder.
func (_u *DocumentACLUpdateOne) Where(ps ...predicate.DocumentACL) *DocumentACLUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DocumentACLUpdateOne) Select(field string, fields ...string) *DocumentACLUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DocumentACL entity.
func (_u *DocumentACLUpdateOne) Save(ctx context.Context) (*DocumentACL, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentACLUpdateOne) SaveX(ctx context.Context) *DocumentACL {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DocumentACLUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentACLUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DocumentACLUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := documentacl.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentACLUpdateOne) check() error {
	if v, ok := _u.mutation.Effect(); ok {
		if err := documentacl.EffectValidator(v); err != nil {
			return &ValidationError{Name: "effect", err: fmt.Errorf(`ent: validator failed for field "DocumentACL.effect": %w`, err)}
		}
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentACL.document"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentACL.group"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DocumentACLUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DocumentACLUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DocumentACLUpdateOne) sqlSave(ctx context.Context) (_node *DocumentACL, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documentacl.Table, documentacl.Columns, sqlgraph.NewFieldSpec(documentacl.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DocumentACL.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, documentacl.FieldID)
		for _, f := range fields {
			if !documentacl.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != documentacl.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Effect(); ok {
		_spec.SetField(documentacl.FieldEffect, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(documentacl.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentacl.DocumentTable,
			Columns: []string{documentacl.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentacl.DocumentTable,
			Columns: []string{documentacl.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentacl.GroupTable,
			Columns: []string{documentacl.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentacl.GroupTable,
			Columns: []string{documentacl.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DocumentACL{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documentacl.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
