// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"document-mdp/ent/documentacl"
	"document-mdp/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DocumentACLDelete is the builder for deleting a DocumentACL entity.
type DocumentACLDelete struct {
	config
	hooks    []Hook
	mutation *DocumentACLMutation
}

// Where appends a list predicates to the DocumentACLDelete builder.
func (_d *DocumentACLDelete) Where(ps ...predicate.DocumentACL) *DocumentACLDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DocumentACLDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DocumentACLDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DocumentACLDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(documentacl.Table, sqlgraph.NewFieldSpec(documentacl.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DocumentACLDeleteOne is the builder for deleting a single DocumentACL entity.
type DocumentACLDeleteOne struct {
	_d *DocumentACLDelete
}

// Where appends a list predicates to the DocumentACLDelete builder.
func (_d *DocumentACLDeleteOne) Where(ps ...predicate.DocumentACL) *DocumentACLDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DocumentACLDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{documentacl.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DocumentACLDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
