// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"document-mdp/ent/documentembedding"
	"document-mdp/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DocumentEmbeddingDelete is the builder for deleting a DocumentEmbedding entity.
type DocumentEmbeddingDelete struct {
	config
	hooks    []Hook
	mutation *DocumentEmbeddingMutation
}

// Where appends a list predicates to the DocumentEmbeddingDelete builder.
func (_d *DocumentEmbeddingDelete) Where(ps ...predicate.DocumentEmbedding) *DocumentEmbeddingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DocumentEmbeddingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DocumentEmbeddingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DocumentEmbeddingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(documentembedding.Table, sqlgraph.NewFieldSpec(documentembedding.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DocumentEmbeddingDeleteOne is the builder for deleting a single DocumentEmbedding entity.
type DocumentEmbeddingDeleteOne struct {
	_d *DocumentEmbeddingDelete
}

// Where appends a list predicates to the DocumentEmbeddingDelete builder.
func (_d *DocumentEmbeddingDeleteOne) Where(ps ...predicate.DocumentEmbedding) *DocumentEmbeddingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DocumentEmbeddingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{documentembedding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DocumentEmbeddingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
