// Code generated by ent, DO NOT EDIT.

package ent

import (
	"document-mdp/ent/document"
	"document-mdp/ent/documentacl"
	"document-mdp/ent/group"
	"document-mdp/ent/schema"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// DocumentACL is the model entity for the DocumentACL schema.
type DocumentACL struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DocumentID holds the value of the "document_id" field.
	DocumentID uuid.UUID `json:"document_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID uuid.UUID `json:"group_id,omitempty"`
	// Effect holds the value of the "effect" field.
	Effect schema.ACLEffect `json:"effect,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DocumentACLQuery when eager-loading is set.
	Edges        DocumentACLEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DocumentACLEdges holds the relations/edges for other nodes in the graph.
type DocumentACLEdges struct {
	// Document holds the value of the document edge.
	Document *Document `json:"document,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// DocumentOrErr returns the Document value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DocumentACLEdges) DocumentOrErr() (*Document, error) {
	if e.Document != nil {
		return e.Document, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: document.Label}
	}
	return nil, &NotLoadedError{edge: "document"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DocumentACLEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DocumentACL) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case documentacl.FieldEffect:
			values[i] = new(sql.NullString)
		case documentacl.FieldCreatedAt, documentacl.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case documentacl.FieldID, documentacl.FieldDocumentID, documentacl.FieldGroupID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DocumentACL fields.
func (_m *DocumentACL) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case documentacl.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case documentacl.FieldDocumentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field document_id", values[i])
			} else if value != nil {
				_m.DocumentID = *value
			}
		case documentacl.FieldGroupID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value != nil {
				_m.GroupID = *value
			}
		case documentacl.FieldEffect:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field effect", values[i])
			} else if value.Valid {
				_m.Effect = schema.ACLEffect(value.String)
			}
		case documentacl.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case documentacl.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DocumentACL.
// This includes values selected through modifiers, order, etc.
func (_m *DocumentACL) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDocument queries the "document" edge of the DocumentACL entity.
func (_m *DocumentACL) QueryDocument() *DocumentQuery {
	return NewDocumentACLClient(_m.config).QueryDocument(_m)
}

// QueryGroup queries the "group" edge of the DocumentACL entity.
func (_m *DocumentACL) QueryGroup() *GroupQuery {
	return NewDocumentACLClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this DocumentACL.
// Note that you need to call DocumentACL.Unwrap() before calling this method if this DocumentACL
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DocumentACL) Update() *DocumentACLUpdateOne {
	return NewDocumentACLClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DocumentACL entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DocumentACL) Unwrap() *DocumentACL {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DocumentACL is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DocumentACL) String() string {
	var builder strings.Builder
	builder.WriteString("DocumentACL(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("document_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DocumentID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("effect=")
	builder.WriteString(fmt.Sprintf("%v", _m.Effect))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DocumentACLs is a parsable slice of DocumentACL.
type DocumentACLs []*DocumentACL
