// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"document-mdp/ent/document"
	"document-mdp/ent/documentembedding"
	"document-mdp/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

// DocumentEmbeddingUpdate is the builder for updating DocumentEmbedding entities.
type DocumentEmbeddingUpdate struct {
	config
	hooks     []Hook
	mutation  *DocumentEmbeddingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DocumentEmbeddingUpdate builder.
func (_u *DocumentEmbeddingUpdate) Where(ps ...predicate.DocumentEmbedding) *DocumentEmbeddingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetModel sets the "model" field.
func (_u *DocumentEmbeddingUpdate) SetModel(v string) *DocumentEmbeddingUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *DocumentEmbeddingUpdate) SetNillableModel(v *string) *DocumentEmbeddingUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetDims sets the "dims" field.
func (_u *DocumentEmbeddingUpdate) SetDims(v int) *DocumentEmbeddingUpdate {
	_u.mutation.ResetDims()
	_u.mutation.SetDims(v)
	return _u
}

// SetNillableDims sets the "dims" field if the given value is not nil.
func (_u *DocumentEmbeddingUpdate) SetNillableDims(v *int) *DocumentEmbeddingUpdate {
	if v != nil {
		_u.SetDims(*v)
	}
	return _u
}

// AddDims adds value to the "dims" field.
func (_u *DocumentEmbeddingUpdate) AddDims(v int) *DocumentEmbeddingUpdate {
	_u.mutation.AddDims(v)
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *DocumentEmbeddingUpdate) SetEmbedding(v pgvector.Vector) *DocumentEmbeddingUpdate {
	_u.mutation.SetEmbedding(v)
	return _u
}

// SetNillableEmbedding sets the "embedding" field if the given value is not nil.
func (_u *DocumentEmbeddingUpdate) SetNillableEmbedding(v *pgvector.Vector) *DocumentEmbeddingUpdate {
	if v != nil {
		_u.SetEmbedding(*v)
	}
	return _u
}

// SetDocumentID sets the "document_id" field.
func (_u *DocumentEmbeddingUpdate) SetDocumentID(v uuid.UUID) *DocumentEmbeddingUpdate {
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *DocumentEmbeddingUpdate) SetNillableDocumentID(v *uuid.UUID) *DocumentEmbeddingUpdate {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// SetDocument sets the "document" edge to the Document entity.
func (_u *DocumentEmbeddingUpdate) SetDocument(v *Document) *DocumentEmbeddingUpdate {
	return _u.SetDocumentID(v.ID)
}

// Mutation returns the DocumentEmbeddingMutation object of the builder.
func (_u *DocumentEmbeddingUpdate) Mutation() *DocumentEmbeddingMutation {
	return _u.mutation
}

// ClearDocument clears the "document" edge to the Document entity.
func (_u *DocumentEmbeddingUpdate) ClearDocument() *DocumentEmbeddingUpdate {
	_u.mutation.ClearDocument()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DocumentEmbeddingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentEmbeddingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DocumentEmbeddingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentEmbeddingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentEmbeddingUpdate) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := documentembedding.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "DocumentEmbedding.model": %w`, err)}
		}
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentEmbedding.document"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DocumentEmbeddingUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DocumentEmbeddingUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DocumentEmbeddingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documentembedding.Table, documentembedding.Columns, sqlgraph.NewFieldSpec(documentembedding.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(documentembedding.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Dims(); ok {
		_spec.SetField(documentembedding.FieldDims, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDims(); ok {
		_spec.AddField(documentembedding.FieldDims, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(documentembedding.FieldEmbedding, field.TypeOther, value)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   documentembedding.DocumentTable,
			Columns: []string{documentembedding.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   documentembedding.DocumentTable,
			Columns: []string{documentembedding.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documentembedding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DocumentEmbeddingUpdateOne is the builder for updating a single DocumentEmbedding entity.
type DocumentEmbeddingUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DocumentEmbeddingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetModel sets the "model" field.
func (_u *DocumentEmbeddingUpdateOne) SetModel(v string) *DocumentEmbeddingUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *DocumentEmbeddingUpdateOne) SetNillableModel(v *string) *DocumentEmbeddingUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetDims sets the "dims" field.
func (_u *DocumentEmbeddingUpdateOne) SetDims(v int) *DocumentEmbeddingUpdateOne {
	_u.mutation.ResetDims()
	_u.mutation.SetDims(v)
	return _u
}

// SetNillableDims sets the "dims" field if the given value is not nil.
func (_u *DocumentEmbeddingUpdateOne) SetNillableDims(v *int) *DocumentEmbeddingUpdateOne {
	if v != nil {
		_u.SetDims(*v)
	}
	return _u
}

// AddDims adds value to the "dims" field.
func (_u *DocumentEmbeddingUpdateOne) AddDims(v int) *DocumentEmbeddingUpdateOne {
	_u.mutation.AddDims(v)
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *DocumentEmbeddingUpdateOne) SetEmbedding(v pgvector.Vector) *DocumentEmbeddingUpdateOne {
	_u.mutation.SetEmbedding(v)
	return _u
}

// SetNillableEmbedding sets the "embedding" field if the given value is not nil.
func (_u *DocumentEmbeddingUpdateOne) SetNillableEmbedding(v *pgvector.Vector) *DocumentEmbeddingUpdateOne {
	if v != nil {
		_u.SetEmbedding(*v)
	}
	return _u
}

// SetDocumentID sets the "document_id" field.
func (_u *DocumentEmbeddingUpdateOne) SetDocumentID(v uuid.UUID) *DocumentEmbeddingUpdateOne {
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *DocumentEmbeddingUpdateOne) SetNillableDocumentID(v *uuid.UUID) *DocumentEmbeddingUpdateOne {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// SetDocument sets the "document" edge to the Document entity.
func (_u *DocumentEmbeddingUpdateOne) SetDocument(v *Document) *DocumentEmbeddingUpdateOne {
	return _u.SetDocumentID(v.ID)
}

// Mutation returns the DocumentEmbeddingMutation object of the builder.
func (_u *DocumentEmbeddingUpdateOne) Mutation() *DocumentEmbeddingMutation {
	return _u.mutation
}

// ClearDocument clears the "document" edge to the Document entity.
func (_u *DocumentEmbeddingUpdateOne) ClearDocument() *DocumentEmbeddingUpdateOne {
	_u.mutation.ClearDocument()
	return _u
}

// Where appends a list predicates to the DocumentEmbeddingUpdate builder.
func (_u *DocumentEmbeddingUpdateOne) Where(ps ...predicate.DocumentEmbedding) *DocumentEmbeddingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DocumentEmbeddingUpdateOne) Select(field string, fields ...string) *DocumentEmbeddingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DocumentEmbedding entity.
func (_u *DocumentEmbeddingUpdateOne) Save(ctx context.Context) (*DocumentEmbedding, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentEmbeddingUpdateOne) SaveX(ctx context.Context) *DocumentEmbedding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DocumentEmbeddingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentEmbeddingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentEmbeddingUpdateOne) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := documentembedding.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "DocumentEmbedding.model": %w`, err)}
		}
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentEmbedding.document"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DocumentEmbeddingUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DocumentEmbeddingUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DocumentEmbeddingUpdateOne) sqlSave(ctx context.Context) (_node *DocumentEmbedding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documentembedding.Table, documentembedding.Columns, sqlgraph.NewFieldSpec(documentembedding.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DocumentEmbedding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, documentembedding.FieldID)
		for _, f := range fields {
			if !documentembedding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != documentembedding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(documentembedding.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Dims(); ok {
		_spec.SetField(documentembedding.FieldDims, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDims(); ok {
		_spec.AddField(documentembedding.FieldDims, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(documentembedding.FieldEmbedding, field.TypeOther, value)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   documentembedding.DocumentTable,
			Columns: []string{documentembedding.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   documentembedding.DocumentTable,
			Columns: []string{documentembedding.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DocumentEmbedding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documentembedding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
