// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"document-mdp/ent/document"
	"document-mdp/ent/documentacl"
	"document-mdp/ent/group"
	"document-mdp/ent/schema"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DocumentACLCreate is the builder for creating a DocumentACL entity.
type DocumentACLCreate struct {
	config
	mutation *DocumentACLMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDocumentID sets the "document_id" field.
func (_c *DocumentACLCreate) SetDocumentID(v uuid.UUID) *DocumentACLCreate {
	_c.mutation.SetDocumentID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *DocumentACLCreate) SetGroupID(v uuid.UUID) *DocumentACLCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetEffect sets the "effect" field.
func (_c *DocumentACLCreate) SetEffect(v schema.ACLEffect) *DocumentACLCreate {
	_c.mutation.SetEffect(v)
	return _c
}

// SetNillableEffect sets the "effect" field if the given value is not nil.
func (_c *DocumentACLCreate) SetNillableEffect(v *schema.ACLEffect) *DocumentACLCreate {
	if v != nil {
		_c.SetEffect(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DocumentACLCreate) SetCreatedAt(v time.Time) *DocumentACLCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DocumentACLCreate) SetNillableCreatedAt(v *time.Time) *DocumentACLCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DocumentACLCreate) SetUpdatedAt(v time.Time) *DocumentACLCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DocumentACLCreate) SetNillableUpdatedAt(v *time.Time) *DocumentACLCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DocumentACLCreate) SetID(v uuid.UUID) *DocumentACLCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DocumentACLCreate) SetNillableID(v *uuid.UUID) *DocumentACLCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetDocument sets the "document" edge to the Document entity.
func (_c *DocumentACLCreate) SetDocument(v *Document) *DocumentACLCreate {
	return _c.SetDocumentID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *DocumentACLCreate) SetGroup(v *Group) *DocumentACLCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the DocumentACLMutation object of the builder.
func (_c *DocumentACLCreate) Mutation() *DocumentACLMutation {
	return _c.mutation
}

// Save creates the DocumentACL in the database.
func (_c *DocumentACLCreate) Save(ctx context.Context) (*DocumentACL, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DocumentACLCreate) SaveX(ctx context.Context) *DocumentACL {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentACLCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentACLCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DocumentACLCreate) defaults() {
	if _, ok := _c.mutation.Effect(); !ok {
		v := documentacl.DefaultEffect
		_c.mutation.SetEffect(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := documentacl.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := documentacl.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := documentacl.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DocumentACLCreate) check() error {
	if _, ok := _c.mutation.DocumentID(); !ok {
		return &ValidationError{Name: "document_id", err: errors.New(`ent: missing required field "DocumentACL.document_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "DocumentACL.group_id"`)}
	}
	if _, ok := _c.mutation.Effect(); !ok {
		return &ValidationError{Name: "effect", err: errors.New(`ent: missing required field "DocumentACL.effect"`)}
	}
	if v, ok := _c.mutation.Effect(); ok {
		if err := documentacl.EffectValidator(v); err != nil {
			return &ValidationError{Name: "effect", err: fmt.Errorf(`ent: validator failed for field "DocumentACL.effect": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DocumentACL.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DocumentACL.updated_at"`)}
	}
	if len(_c.mutation.DocumentIDs()) == 0 {
		return &ValidationError{Name: "document", err: errors.New(`ent: missing required edge "DocumentACL.document"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "DocumentACL.group"`)}
	}
	return nil
}

func (_c *DocumentACLCreate) sqlSave(ctx context.Context) (*DocumentACL, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DocumentACLCreate) createSpec() (*DocumentACL, *sqlgraph.CreateSpec) {
	var (
		_node = &DocumentACL{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(documentacl.Table, sqlgraph.NewFieldSpec(documentacl.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Effect(); ok {
		_spec.SetField(documentacl.FieldEffect, field.TypeEnum, value)
		_node.Effect = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(documentacl.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(documentacl.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentacl.DocumentTable,
			Columns: []string{documentacl.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DocumentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentacl.GroupTable,
			Columns: []string{documentacl.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DocumentACL.Create().
//		SetDocumentID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DocumentACLUpsert) {
//			SetDocumentID(v+v).
//		}).
//		Exec(ctx)
func (_c *DocumentACLCreate) OnConflict(opts ...sql.ConflictOption) *DocumentACLUpsertOne {
	_c.conflict = opts
	return &DocumentACLUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DocumentACL.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DocumentACLCreate) OnConflictColumns(columns ...string) *DocumentACLUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DocumentACLUpsertOne{
		create: _c,
	}
}

type (
	// DocumentACLUpsertOne is the builder for "upsert"-ing
	//  one DocumentACL node.
	DocumentACLUpsertOne struct {
		create *DocumentACLCreate
	}

	// DocumentACLUpsert is the "OnConflict" setter.
	DocumentACLUpsert struct {
		*sql.UpdateSet
	}
)

// SetDocumentID sets the "document_id" field.
func (u *DocumentACLUpsert) SetDocumentID(v uuid.UUID) *DocumentACLUpsert {
	u.Set(documentacl.FieldDocumentID, v)
	return u
}

// UpdateDocumentID sets the "document_id" field to the value that was provided on create.
func (u *DocumentACLUpsert) UpdateDocumentID() *DocumentACLUpsert {
	u.SetExcluded(documentacl.FieldDocumentID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *DocumentACLUpsert) SetGroupID(v uuid.UUID) *DocumentACLUpsert {
	u.Set(documentacl.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DocumentACLUpsert) UpdateGroupID() *DocumentACLUpsert {
	u.SetExcluded(documentacl.FieldGroupID)
	return u
}

// SetEffect sets the "effect" field.
func (u *DocumentACLUpsert) SetEffect(v schema.ACLEffect) *DocumentACLUpsert {
	u.Set(documentacl.FieldEffect, v)
	return u
}

// UpdateEffect sets the "effect" field to the value that was provided on create.
func (u *DocumentACLUpsert) UpdateEffect() *DocumentACLUpsert {
	u.SetExcluded(documentacl.FieldEffect)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DocumentACLUpsert) SetUpdatedAt(v time.Time) *DocumentACLUpsert {
	u.Set(documentacl.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DocumentACLUpsert) UpdateUpdatedAt() *DocumentACLUpsert {
	u.SetExcluded(documentacl.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DocumentACL.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(documentacl.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DocumentACLUpsertOne) UpdateNewValues() *DocumentACLUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(documentacl.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(documentacl.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DocumentACL.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DocumentACLUpsertOne) Ignore() *DocumentACLUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DocumentACLUpsertOne) DoNothing() *DocumentACLUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DocumentACLCreate.OnConflict
// documentation for more info.
func (u *DocumentACLUpsertOne) Update(set func(*DocumentACLUpsert)) *DocumentACLUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DocumentACLUpsert{UpdateSet: update})
	}))
	return u
}

// SetDocumentID sets the "document_id" field.
func (u *DocumentACLUpsertOne) SetDocumentID(v uuid.UUID) *DocumentACLUpsertOne {
	return u.Update(func(s *DocumentACLUpsert) {
		s.SetDocumentID(v)
	})
}

// UpdateDocumentID sets the "document_id" field to the value that was provided on create.
func (u *DocumentACLUpsertOne) UpdateDocumentID() *DocumentACLUpsertOne {
	return u.Update(func(s *DocumentACLUpsert) {
		s.UpdateDocumentID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *DocumentACLUpsertOne) SetGroupID(v uuid.UUID) *DocumentACLUpsertOne {
	return u.Update(func(s *DocumentACLUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DocumentACLUpsertOne) UpdateGroupID() *DocumentACLUpsertOne {
	return u.Update(func(s *DocumentACLUpsert) {
		s.UpdateGroupID()
	})
}

// SetEffect sets the "effect" field.
func (u *DocumentACLUpsertOne) SetEffect(v schema.ACLEffect) *DocumentACLUpsertOne {
	return u.Update(func(s *DocumentACLUpsert) {
		s.SetEffect(v)
	})
}

// UpdateEffect sets the "effect" field to the value that was provided on create.
func (u *DocumentACLUpsertOne) UpdateEffect() *DocumentACLUpsertOne {
	return u.Update(func(s *DocumentACLUpsert) {
		s.UpdateEffect()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DocumentACLUpsertOne) SetUpdatedAt(v time.Time) *DocumentACLUpsertOne {
	return u.Update(func(s *DocumentACLUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DocumentACLUpsertOne) UpdateUpdatedAt() *DocumentACLUpsertOne {
	return u.Update(func(s *DocumentACLUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DocumentACLUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DocumentACLCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DocumentACLUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DocumentACLUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DocumentACLUpsertOne.ID is not supported by MySQL driver. Use DocumentACLUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DocumentACLUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DocumentACLCreateBulk is the builder for creating many DocumentACL entities in bulk.
type DocumentACLCreateBulk struct {
	config
	err      error
	builders []*DocumentACLCreate
	conflict []sql.ConflictOption
}

// Save creates the DocumentACL entities in the database.
func (_c *DocumentACLCreateBulk) Save(ctx context.Context) ([]*DocumentACL, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DocumentACL, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DocumentACLMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DocumentACLCreateBulk) SaveX(ctx context.Context) []*DocumentACL {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentACLCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentACLCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DocumentACL.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DocumentACLUpsert) {
//			SetDocumentID(v+v).
//		}).
//		Exec(ctx)
func (_c *DocumentACLCreateBulk) OnConflict(opts ...sql.ConflictOption) *DocumentACLUpsertBulk {
	_c.conflict = opts
	return &DocumentACLUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DocumentACL.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DocumentACLCreateBulk) OnConflictColumns(columns ...string) *DocumentACLUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DocumentACLUpsertBulk{
		create: _c,
	}
}

// DocumentACLUpsertBulk is the builder for "upsert"-ing
// a bulk of DocumentACL nodes.
type DocumentACLUpsertBulk struct {
	create *DocumentACLCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DocumentACL.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(documentacl.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DocumentACLUpsertBulk) UpdateNewValues() *DocumentACLUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(documentacl.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(documentacl.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DocumentACL.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DocumentACLUpsertBulk) Ignore() *DocumentACLUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DocumentACLUpsertBulk) DoNothing() *DocumentACLUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DocumentACLCreateBulk.OnConflict
// documentation for more info.
func (u *DocumentACLUpsertBulk) Update(set func(*DocumentACLUpsert)) *DocumentACLUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DocumentACLUpsert{UpdateSet: update})
	}))
	return u
}

// SetDocumentID sets the "document_id" field.
func (u *DocumentACLUpsertBulk) SetDocumentID(v uuid.UUID) *DocumentACLUpsertBulk {
	return u.Update(func(s *DocumentACLUpsert) {
		s.SetDocumentID(v)
	})
}

// UpdateDocumentID sets the "document_id" field to the value that was provided on create.
func (u *DocumentACLUpsertBulk) UpdateDocumentID() *DocumentACLUpsertBulk {
	return u.Update(func(s *DocumentACLUpsert) {
		s.UpdateDocumentID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *DocumentACLUpsertBulk) SetGroupID(v uuid.UUID) *DocumentACLUpsertBulk {
	return u.Update(func(s *DocumentACLUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DocumentACLUpsertBulk) UpdateGroupID() *DocumentACLUpsertBulk {
	return u.Update(func(s *DocumentACLUpsert) {
		s.UpdateGroupID()
	})
}

// SetEffect sets the "effect" field.
func (u *DocumentACLUpsertBulk) SetEffect(v schema.ACLEffect) *DocumentACLUpsertBulk {
	return u.Update(func(s *DocumentACLUpsert) {
		s.SetEffect(v)
	})
}

// UpdateEffect sets the "effect" field to the value that was provided on create.
func (u *DocumentACLUpsertBulk) UpdateEffect() *DocumentACLUpsertBulk {
	return u.Update(func(s *DocumentACLUpsert) {
		s.UpdateEffect()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DocumentACLUpsertBulk) SetUpdatedAt(v time.Time) *DocumentACLUpsertBulk {
	return u.Update(func(s *DocumentACLUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DocumentACLUpsertBulk) UpdateUpdatedAt() *DocumentACLUpsertBulk {
	return u.Update(func(s *DocumentACLUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DocumentACLUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DocumentACLCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DocumentACLCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DocumentACLUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
