// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"document-mdp/ent/document"
	"document-mdp/ent/documentacl"
	"document-mdp/ent/documentalias"
	"document-mdp/ent/documentembedding"
	"document-mdp/ent/predicate"
	"document-mdp/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DocumentUpdate is the builder for updating Document entities.
type DocumentUpdate struct {
	config
	hooks     []Hook
	mutation  *DocumentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DocumentUpdate builder.
func (_u *DocumentUpdate) Where(ps ...predicate.Document) *DocumentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetYear sets the "year" field.
func (_u *DocumentUpdate) SetYear(v int) *DocumentUpdate {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableYear(v *int) *DocumentUpdate {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *DocumentUpdate) AddYear(v int) *DocumentUpdate {
	_u.mutation.AddYear(v)
	return _u
}

// SetDepth1 sets the "depth1" field.
func (_u *DocumentUpdate) SetDepth1(v string) *DocumentUpdate {
	_u.mutation.SetDepth1(v)
	return _u
}

// SetNillableDepth1 sets the "depth1" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableDepth1(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetDepth1(*v)
	}
	return _u
}

// SetDepth2 sets the "depth2" field.
func (_u *DocumentUpdate) SetDepth2(v string) *DocumentUpdate {
	_u.mutation.SetDepth2(v)
	return _u
}

// SetNillableDepth2 sets the "depth2" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableDepth2(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetDepth2(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *DocumentUpdate) SetTitle(v string) *DocumentUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableTitle(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *DocumentUpdate) SetContent(v string) *DocumentUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableContent(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *DocumentUpdate) ClearContent() *DocumentUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DocumentUpdate) SetUpdatedAt(v time.Time) *DocumentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *DocumentUpdate) SetCreatedByUserID(v uuid.UUID) *DocumentUpdate {
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableCreatedByUserID(v *uuid.UUID) *DocumentUpdate {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_u *DocumentUpdate) SetCreatedByID(id uuid.UUID) *DocumentUpdate {
	_u.mutation.SetCreatedByID(id)
	return _u
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_u *DocumentUpdate) SetCreatedBy(v *User) *DocumentUpdate {
	return _u.SetCreatedByID(v.ID)
}

// AddAliasIDs adds the "aliases" edge to the DocumentAlias entity by IDs.
func (_u *DocumentUpdate) AddAliasIDs(ids ...uuid.UUID) *DocumentUpdate {
	_u.mutation.AddAliasIDs(ids...)
	return _u
}

// AddAliases adds the "aliases" edges to the DocumentAlias entity.
func (_u *DocumentUpdate) AddAliases(v ...*DocumentAlias) *DocumentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAliasIDs(ids...)
}

// SetEmbeddingID sets the "embedding" edge to the DocumentEmbedding entity by ID.
func (_u *DocumentUpdate) SetEmbeddingID(id uuid.UUID) *DocumentUpdate {
	_u.mutation.SetEmbeddingID(id)
	return _u
}

// SetNillableEmbeddingID sets the "embedding" edge to the DocumentEmbedding entity by ID if the given value is not nil.
func (_u *DocumentUpdate) SetNillableEmbeddingID(id *uuid.UUID) *DocumentUpdate {
	if id != nil {
		_u = _u.SetEmbeddingID(*id)
	}
	return _u
}

// SetEmbedding sets the "embedding" edge to the DocumentEmbedding entity.
func (_u *DocumentUpdate) SetEmbedding(v *DocumentEmbedding) *DocumentUpdate {
	return _u.SetEmbeddingID(v.ID)
}

// AddACLIDs adds the "acls" edge to the DocumentACL entity by IDs.
func (_u *DocumentUpdate) AddACLIDs(ids ...uuid.UUID) *DocumentUpdate {
	_u.mutation.AddACLIDs(ids...)
	return _u
}

// AddAcls adds the "acls" edges to the DocumentACL entity.
func (_u *DocumentUpdate) AddAcls(v ...*DocumentACL) *DocumentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddACLIDs(ids...)
}

// Mutation returns the DocumentMutation object of the builder.
func (_u *DocumentUpdate) Mutation() *DocumentMutation {
	return _u.mutation
}

// ClearCreatedBy clears the "created_by" edge to the User entity.
func (_u *DocumentUpdate) ClearCreatedBy() *DocumentUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// ClearAliases clears all "aliases" edges to the DocumentAlias entity.
func (_u *DocumentUpdate) ClearAliases() *DocumentUpdate {
	_u.mutation.ClearAliases()
	return _u
}

// RemoveAliasIDs removes the "aliases" edge to DocumentAlias entities by IDs.
func (_u *DocumentUpdate) RemoveAliasIDs(ids ...uuid.UUID) *DocumentUpdate {
	_u.mutation.RemoveAliasIDs(ids...)
	return _u
}

// RemoveAliases removes "aliases" edges to DocumentAlias entities.
func (_u *DocumentUpdate) RemoveAliases(v ...*DocumentAlias) *DocumentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAliasIDs(ids...)
}

// ClearEmbedding clears the "embedding" edge to the DocumentEmbedding entity.
func (_u *DocumentUpdate) ClearEmbedding() *DocumentUpdate {
	_u.mutation.ClearEmbedding()
	return _u
}

// ClearAcls clears all "acls" edges to the DocumentACL entity.
func (_u *DocumentUpdate) ClearAcls() *DocumentUpdate {
	_u.mutation.ClearAcls()
	return _u
}

// RemoveACLIDs removes the "acls" edge to DocumentACL entities by IDs.
func (_u *DocumentUpdate) RemoveACLIDs(ids ...uuid.UUID) *DocumentUpdate {
	_u.mutation.RemoveACLIDs(ids...)
	return _u
}

// RemoveAcls removes "acls" edges to DocumentACL entities.
func (_u *DocumentUpdate) RemoveAcls(v ...*DocumentACL) *DocumentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveACLIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DocumentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DocumentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DocumentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := document.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentUpdate) check() error {
	if v, ok := _u.mutation.Depth1(); ok {
		if err := document.Depth1Validator(v); err != nil {
			return &ValidationError{Name: "depth1", err: fmt.Errorf(`ent: validator failed for field "Document.depth1": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Depth2(); ok {
		if err := document.Depth2Validator(v); err != nil {
			return &ValidationError{Name: "depth2", err: fmt.Errorf(`ent: validator failed for field "Document.depth2": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := document.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Document.title": %w`, err)}
		}
	}
	if _u.mutation.CreatedByCleared() && len(_u.mutation.CreatedByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Document.created_by"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DocumentUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DocumentUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DocumentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(document.Table, document.Columns, sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(document.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(document.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Depth1(); ok {
		_spec.SetField(document.FieldDepth1, field.TypeString, value)
	}
	if value, ok := _u.mutation.Depth2(); ok {
		_spec.SetField(document.FieldDepth2, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(document.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(document.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(document.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(document.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.CreatedByTable,
			Columns: []string{document.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.CreatedByTable,
			Columns: []string{document.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AliasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.AliasesTable,
			Columns: []string{document.AliasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentalias.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAliasesIDs(); len(nodes) > 0 && !_u.mutation.AliasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.AliasesTable,
			Columns: []string{document.AliasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentalias.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AliasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.AliasesTable,
			Columns: []string{document.AliasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentalias.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmbeddingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   document.EmbeddingTable,
			Columns: []string{document.EmbeddingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentembedding.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmbeddingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   document.EmbeddingTable,
			Columns: []string{document.EmbeddingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentembedding.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AclsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.AclsTable,
			Columns: []string{document.AclsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentacl.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAclsIDs(); len(nodes) > 0 && !_u.mutation.AclsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.AclsTable,
			Columns: []string{document.AclsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentacl.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AclsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.AclsTable,
			Columns: []string{document.AclsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentacl.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{document.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DocumentUpdateOne is the builder for updating a single Document entity.
type DocumentUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DocumentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetYear sets the "year" field.
func (_u *DocumentUpdateOne) SetYear(v int) *DocumentUpdateOne {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableYear(v *int) *DocumentUpdateOne {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *DocumentUpdateOne) AddYear(v int) *DocumentUpdateOne {
	_u.mutation.AddYear(v)
	return _u
}

// SetDepth1 sets the "depth1" field.
func (_u *DocumentUpdateOne) SetDepth1(v string) *DocumentUpdateOne {
	_u.mutation.SetDepth1(v)
	return _u
}

// SetNillableDepth1 sets the "depth1" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableDepth1(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetDepth1(*v)
	}
	return _u
}

// SetDepth2 sets the "depth2" field.
func (_u *DocumentUpdateOne) SetDepth2(v string) *DocumentUpdateOne {
	_u.mutation.SetDepth2(v)
	return _u
}

// SetNillableDepth2 sets the "depth2" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableDepth2(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetDepth2(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *DocumentUpdateOne) SetTitle(v string) *DocumentUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableTitle(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *DocumentUpdateOne) SetContent(v string) *DocumentUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableContent(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *DocumentUpdateOne) ClearContent() *DocumentUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DocumentUpdateOne) SetUpdatedAt(v time.Time) *DocumentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *DocumentUpdateOne) SetCreatedByUserID(v uuid.UUID) *DocumentUpdateOne {
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableCreatedByUserID(v *uuid.UUID) *DocumentUpdateOne {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_u *DocumentUpdateOne) SetCreatedByID(id uuid.UUID) *DocumentUpdateOne {
	_u.mutation.SetCreatedByID(id)
	return _u
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_u *DocumentUpdateOne) SetCreatedBy(v *User) *DocumentUpdateOne {
	return _u.SetCreatedByID(v.ID)
}

// AddAliasIDs adds the "aliases" edge to the DocumentAlias entity by IDs.
func (_u *DocumentUpdateOne) AddAliasIDs(ids ...uuid.UUID) *DocumentUpdateOne {
	_u.mutation.AddAliasIDs(ids...)
	return _u
}

// AddAliases adds the "aliases" edges to the DocumentAlias entity.
func (_u *DocumentUpdateOne) AddAliases(v ...*DocumentAlias) *DocumentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAliasIDs(ids...)
}

// SetEmbeddingID sets the "embedding" edge to the DocumentEmbedding entity by ID.
func (_u *DocumentUpdateOne) SetEmbeddingID(id uuid.UUID) *DocumentUpdateOne {
	_u.mutation.SetEmbeddingID(id)
	return _u
}

// SetNillableEmbeddingID sets the "embedding" edge to the DocumentEmbedding entity by ID if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableEmbeddingID(id *uuid.UUID) *DocumentUpdateOne {
	if id != nil {
		_u = _u.SetEmbeddingID(*id)
	}
	return _u
}

// SetEmbedding sets the "embedding" edge to the DocumentEmbedding entity.
func (_u *DocumentUpdateOne) SetEmbedding(v *DocumentEmbedding) *DocumentUpdateOne {
	return _u.SetEmbeddingID(v.ID)
}

// AddACLIDs adds the "acls" edge to the DocumentACL entity by IDs.
func (_u *DocumentUpdateOne) AddACLIDs(ids ...uuid.UUID) *DocumentUpdateOne {
	_u.mutation.AddACLIDs(ids...)
	return _u
}

// AddAcls adds the "acls" edges to the DocumentACL entity.
func (_u *DocumentUpdateOne) AddAcls(v ...*DocumentACL) *DocumentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddACLIDs(ids...)
}

// Mutation returns the DocumentMutation object of the builder.
func (_u *DocumentUpdateOne) Mutation() *DocumentMutation {
	return _u.mutation
}

// ClearCreatedBy clears the "created_by" edge to the User entity.
func (_u *DocumentUpdateOne) ClearCreatedBy() *DocumentUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// ClearAliases clears all "aliases" edges to the DocumentAlias entity.
func (_u *DocumentUpdateOne) ClearAliases() *DocumentUpdateOne {
	_u.mutation.ClearAliases()
	return _u
}

// RemoveAliasIDs removes the "aliases" edge to DocumentAlias entities by IDs.
func (_u *DocumentUpdateOne) RemoveAliasIDs(ids ...uuid.UUID) *DocumentUpdateOne {
	_u.mutation.RemoveAliasIDs(ids...)
	return _u
}

// RemoveAliases removes "aliases" edges to DocumentAlias entities.
func (_u *DocumentUpdateOne) RemoveAliases(v ...*DocumentAlias) *DocumentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAliasIDs(ids...)
}

// ClearEmbedding clears the "embedding" edge to the DocumentEmbedding entity.
func (_u *DocumentUpdateOne) ClearEmbedding() *DocumentUpdateOne {
	_u.mutation.ClearEmbedding()
	return _u
}

// ClearAcls clears all "acls" edges to the DocumentACL entity.
func (_u *DocumentUpdateOne) ClearAcls() *DocumentUpdateOne {
	_u.mutation.ClearAcls()
	return _u
}

// RemoveACLIDs removes the "acls" edge to DocumentACL entities by IDs.
func (_u *DocumentUpdateOne) RemoveACLIDs(ids ...uuid.UUID) *DocumentUpdateOne {
	_u.mutation.RemoveACLIDs(ids...)
	return _u
}

// RemoveAcls removes "acls" edges to DocumentACL entities.
func (_u *DocumentUpdateOne) RemoveAcls(v ...*DocumentACL) *DocumentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveACLIDs(ids...)
}

// Where appends a list predicates to the DocumentUpdate builder.
func (_u *DocumentUpdateOne) Where(ps ...predicate.Document) *DocumentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DocumentUpdateOne) Select(field string, fields ...string) *DocumentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Document entity.
func (_u *DocumentUpdateOne) Save(ctx context.Context) (*Document, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentUpdateOne) SaveX(ctx context.Context) *Document {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DocumentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DocumentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := document.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentUpdateOne) check() error {
	if v, ok := _u.mutation.Depth1(); ok {
		if err := document.Depth1Validator(v); err != nil {
			return &ValidationError{Name: "depth1", err: fmt.Errorf(`ent: validator failed for field "Document.depth1": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Depth2(); ok {
		if err := document.Depth2Validator(v); err != nil {
			return &ValidationError{Name: "depth2", err: fmt.Errorf(`ent: validator failed for field "Document.depth2": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := document.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Document.title": %w`, err)}
		}
	}
	if _u.mutation.CreatedByCleared() && len(_u.mutation.CreatedByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Document.created_by"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DocumentUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DocumentUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DocumentUpdateOne) sqlSave(ctx context.Context) (_node *Document, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(document.Table, document.Columns, sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Document.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, document.FieldID)
		for _, f := range fields {
			if !document.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != document.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(document.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(document.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Depth1(); ok {
		_spec.SetField(document.FieldDepth1, field.TypeString, value)
	}
	if value, ok := _u.mutation.Depth2(); ok {
		_spec.SetField(document.FieldDepth2, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(document.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(document.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(document.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(document.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.CreatedByTable,
			Columns: []string{document.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.CreatedByTable,
			Columns: []string{document.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AliasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.AliasesTable,
			Columns: []string{document.AliasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentalias.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAliasesIDs(); len(nodes) > 0 && !_u.mutation.AliasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.AliasesTable,
			Columns: []string{document.AliasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentalias.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AliasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.AliasesTable,
			Columns: []string{document.AliasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentalias.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmbeddingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   document.EmbeddingTable,
			Columns: []string{document.EmbeddingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentembedding.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmbeddingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   document.EmbeddingTable,
			Columns: []string{document.EmbeddingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentembedding.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AclsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.AclsTable,
			Columns: []string{document.AclsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentacl.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAclsIDs(); len(nodes) > 0 && !_u.mutation.AclsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.AclsTable,
			Columns: []string{document.AclsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentacl.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AclsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.AclsTable,
			Columns: []string{document.AclsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentacl.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Document{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{document.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
