// Code generated by ent, DO NOT EDIT.

package ent

import (
	"document-mdp/ent/document"
	"document-mdp/ent/documentembedding"
	"document-mdp/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Document is the model entity for the Document schema.
type Document struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Year holds the value of the "year" field.
	Year int `json:"year,omitempty"`
	// Depth1 holds the value of the "depth1" field.
	Depth1 string `json:"depth1,omitempty"`
	// Depth2 holds the value of the "depth2" field.
	Depth2 string `json:"depth2,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedByUserID holds the value of the "created_by_user_id" field.
	CreatedByUserID uuid.UUID `json:"created_by_user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DocumentQuery when eager-loading is set.
	Edges        DocumentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DocumentEdges holds the relations/edges for other nodes in the graph.
type DocumentEdges struct {
	// CreatedBy holds the value of the created_by edge.
	CreatedBy *User `json:"created_by,omitempty"`
	// Aliases holds the value of the aliases edge.
	Aliases []*DocumentAlias `json:"aliases,omitempty"`
	// Embedding holds the value of the embedding edge.
	Embedding *DocumentEmbedding `json:"embedding,omitempty"`
	// Acls holds the value of the acls edge.
	Acls []*DocumentACL `json:"acls,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// CreatedByOrErr returns the CreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DocumentEdges) CreatedByOrErr() (*User, error) {
	if e.CreatedBy != nil {
		return e.CreatedBy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "created_by"}
}

// AliasesOrErr returns the Aliases value or an error if the edge
// was not loaded in eager-loading.
func (e DocumentEdges) AliasesOrErr() ([]*DocumentAlias, error) {
	if e.loadedTypes[1] {
		return e.Aliases, nil
	}
	return nil, &NotLoadedError{edge: "aliases"}
}

// EmbeddingOrErr returns the Embedding value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DocumentEdges) EmbeddingOrErr() (*DocumentEmbedding, error) {
	if e.Embedding != nil {
		return e.Embedding, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: documentembedding.Label}
	}
	return nil, &NotLoadedError{edge: "embedding"}
}

// AclsOrErr returns the Acls value or an error if the edge
// was not loaded in eager-loading.
func (e DocumentEdges) AclsOrErr() ([]*DocumentACL, error) {
	if e.loadedTypes[3] {
		return e.Acls, nil
	}
	return nil, &NotLoadedError{edge: "acls"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Document) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case document.FieldYear:
			values[i] = new(sql.NullInt64)
		case document.FieldDepth1, document.FieldDepth2, document.FieldTitle, document.FieldContent:
			values[i] = new(sql.NullString)
		case document.FieldCreatedAt, document.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case document.FieldID, document.FieldCreatedByUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Document fields.
func (_m *Document) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case document.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case document.FieldYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field year", values[i])
			} else if value.Valid {
				_m.Year = int(value.Int64)
			}
		case document.FieldDepth1:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field depth1", values[i])
			} else if value.Valid {
				_m.Depth1 = value.String
			}
		case document.FieldDepth2:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field depth2", values[i])
			} else if value.Valid {
				_m.Depth2 = value.String
			}
		case document.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case document.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case document.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case document.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case document.FieldCreatedByUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_user_id", values[i])
			} else if value != nil {
				_m.CreatedByUserID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Document.
// This includes values selected through modifiers, order, etc.
func (_m *Document) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCreatedBy queries the "created_by" edge of the Document entity.
func (_m *Document) QueryCreatedBy() *UserQuery {
	return NewDocumentClient(_m.config).QueryCreatedBy(_m)
}

// QueryAliases queries the "aliases" edge of the Document entity.
func (_m *Document) QueryAliases() *DocumentAliasQuery {
	return NewDocumentClient(_m.config).QueryAliases(_m)
}

// QueryEmbedding queries the "embedding" edge of the Document entity.
func (_m *Document) QueryEmbedding() *DocumentEmbeddingQuery {
	return NewDocumentClient(_m.config).QueryEmbedding(_m)
}

// QueryAcls queries the "acls" edge of the Document entity.
func (_m *Document) QueryAcls() *DocumentACLQuery {
	return NewDocumentClient(_m.config).QueryAcls(_m)
}

// Update returns a builder for updating this Document.
// Note that you need to call Document.Unwrap() before calling this method if this Document
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Document) Update() *DocumentUpdateOne {
	return NewDocumentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Document entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Document) Unwrap() *Document {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Document is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Document) String() string {
	var builder strings.Builder
	builder.WriteString("Document(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("year=")
	builder.WriteString(fmt.Sprintf("%v", _m.Year))
	builder.WriteString(", ")
	builder.WriteString("depth1=")
	builder.WriteString(_m.Depth1)
	builder.WriteString(", ")
	builder.WriteString("depth2=")
	builder.WriteString(_m.Depth2)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedByUserID))
	builder.WriteByte(')')
	return builder.String()
}

// Documents is a parsable slice of Document.
type Documents []*Document
