// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"document-mdp/ent/document"
	"document-mdp/ent/documentacl"
	"document-mdp/ent/documentalias"
	"document-mdp/ent/documentembedding"
	"document-mdp/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DocumentCreate is the builder for creating a Document entity.
type DocumentCreate struct {
	config
	mutation *DocumentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetYear sets the "year" field.
func (_c *DocumentCreate) SetYear(v int) *DocumentCreate {
	_c.mutation.SetYear(v)
	return _c
}

// SetDepth1 sets the "depth1" field.
func (_c *DocumentCreate) SetDepth1(v string) *DocumentCreate {
	_c.mutation.SetDepth1(v)
	return _c
}

// SetDepth2 sets the "depth2" field.
func (_c *DocumentCreate) SetDepth2(v string) *DocumentCreate {
	_c.mutation.SetDepth2(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *DocumentCreate) SetTitle(v string) *DocumentCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *DocumentCreate) SetContent(v string) *DocumentCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableContent(v *string) *DocumentCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DocumentCreate) SetCreatedAt(v time.Time) *DocumentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableCreatedAt(v *time.Time) *DocumentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DocumentCreate) SetUpdatedAt(v time.Time) *DocumentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableUpdatedAt(v *time.Time) *DocumentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_c *DocumentCreate) SetCreatedByUserID(v uuid.UUID) *DocumentCreate {
	_c.mutation.SetCreatedByUserID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DocumentCreate) SetID(v uuid.UUID) *DocumentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableID(v *uuid.UUID) *DocumentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_c *DocumentCreate) SetCreatedByID(id uuid.UUID) *DocumentCreate {
	_c.mutation.SetCreatedByID(id)
	return _c
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_c *DocumentCreate) SetCreatedBy(v *User) *DocumentCreate {
	return _c.SetCreatedByID(v.ID)
}

// AddAliasIDs adds the "aliases" edge to the DocumentAlias entity by IDs.
func (_c *DocumentCreate) AddAliasIDs(ids ...uuid.UUID) *DocumentCreate {
	_c.mutation.AddAliasIDs(ids...)
	return _c
}

// AddAliases adds the "aliases" edges to the DocumentAlias entity.
func (_c *DocumentCreate) AddAliases(v ...*DocumentAlias) *DocumentCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAliasIDs(ids...)
}

// SetEmbeddingID sets the "embedding" edge to the DocumentEmbedding entity by ID.
func (_c *DocumentCreate) SetEmbeddingID(id uuid.UUID) *DocumentCreate {
	_c.mutation.SetEmbeddingID(id)
	return _c
}

// SetNillableEmbeddingID sets the "embedding" edge to the DocumentEmbedding entity by ID if the given value is not nil.
func (_c *DocumentCreate) SetNillableEmbeddingID(id *uuid.UUID) *DocumentCreate {
	if id != nil {
		_c = _c.SetEmbeddingID(*id)
	}
	return _c
}

// SetEmbedding sets the "embedding" edge to the DocumentEmbedding entity.
func (_c *DocumentCreate) SetEmbedding(v *DocumentEmbedding) *DocumentCreate {
	return _c.SetEmbeddingID(v.ID)
}

// AddACLIDs adds the "acls" edge to the DocumentACL entity by IDs.
func (_c *DocumentCreate) AddACLIDs(ids ...uuid.UUID) *DocumentCreate {
	_c.mutation.AddACLIDs(ids...)
	return _c
}

// AddAcls adds the "acls" edges to the DocumentACL entity.
func (_c *DocumentCreate) AddAcls(v ...*DocumentACL) *DocumentCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddACLIDs(ids...)
}

// Mutation returns the DocumentMutation object of the builder.
func (_c *DocumentCreate) Mutation() *DocumentMutation {
	return _c.mutation
}

// Save creates the Document in the database.
func (_c *DocumentCreate) Save(ctx context.Context) (*Document, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DocumentCreate) SaveX(ctx context.Context) *Document {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DocumentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := document.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := document.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := document.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DocumentCreate) check() error {
	if _, ok := _c.mutation.Year(); !ok {
		return &ValidationError{Name: "year", err: errors.New(`ent: missing required field "Document.year"`)}
	}
	if _, ok := _c.mutation.Depth1(); !ok {
		return &ValidationError{Name: "depth1", err: errors.New(`ent: missing required field "Document.depth1"`)}
	}
	if v, ok := _c.mutation.Depth1(); ok {
		if err := document.Depth1Validator(v); err != nil {
			return &ValidationError{Name: "depth1", err: fmt.Errorf(`ent: validator failed for field "Document.depth1": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Depth2(); !ok {
		return &ValidationError{Name: "depth2", err: errors.New(`ent: missing required field "Document.depth2"`)}
	}
	if v, ok := _c.mutation.Depth2(); ok {
		if err := document.Depth2Validator(v); err != nil {
			return &ValidationError{Name: "depth2", err: fmt.Errorf(`ent: validator failed for field "Document.depth2": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Document.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := document.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Document.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Document.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Document.updated_at"`)}
	}
	if _, ok := _c.mutation.CreatedByUserID(); !ok {
		return &ValidationError{Name: "created_by_user_id", err: errors.New(`ent: missing required field "Document.created_by_user_id"`)}
	}
	if len(_c.mutation.CreatedByIDs()) == 0 {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required edge "Document.created_by"`)}
	}
	return nil
}

func (_c *DocumentCreate) sqlSave(ctx context.Context) (*Document, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DocumentCreate) createSpec() (*Document, *sqlgraph.CreateSpec) {
	var (
		_node = &Document{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(document.Table, sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Year(); ok {
		_spec.SetField(document.FieldYear, field.TypeInt, value)
		_node.Year = value
	}
	if value, ok := _c.mutation.Depth1(); ok {
		_spec.SetField(document.FieldDepth1, field.TypeString, value)
		_node.Depth1 = value
	}
	if value, ok := _c.mutation.Depth2(); ok {
		_spec.SetField(document.FieldDepth2, field.TypeString, value)
		_node.Depth2 = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(document.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(document.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(document.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(document.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.CreatedByTable,
			Columns: []string{document.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedByUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AliasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.AliasesTable,
			Columns: []string{document.AliasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentalias.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EmbeddingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   document.EmbeddingTable,
			Columns: []string{document.EmbeddingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentembedding.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AclsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.AclsTable,
			Columns: []string{document.AclsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentacl.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Document.Create().
//		SetYear(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DocumentUpsert) {
//			SetYear(v+v).
//		}).
//		Exec(ctx)
func (_c *DocumentCreate) OnConflict(opts ...sql.ConflictOption) *DocumentUpsertOne {
	_c.conflict = opts
	return &DocumentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Document.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DocumentCreate) OnConflictColumns(columns ...string) *DocumentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DocumentUpsertOne{
		create: _c,
	}
}

type (
	// DocumentUpsertOne is the builder for "upsert"-ing
	//  one Document node.
	DocumentUpsertOne struct {
		create *DocumentCreate
	}

	// DocumentUpsert is the "OnConflict" setter.
	DocumentUpsert struct {
		*sql.UpdateSet
	}
)

// SetYear sets the "year" field.
func (u *DocumentUpsert) SetYear(v int) *DocumentUpsert {
	u.Set(document.FieldYear, v)
	return u
}

// UpdateYear sets the "year" field to the value that was provided on create.
func (u *DocumentUpsert) UpdateYear() *DocumentUpsert {
	u.SetExcluded(document.FieldYear)
	return u
}

// AddYear adds v to the "year" field.
func (u *DocumentUpsert) AddYear(v int) *DocumentUpsert {
	u.Add(document.FieldYear, v)
	return u
}

// SetDepth1 sets the "depth1" field.
func (u *DocumentUpsert) SetDepth1(v string) *DocumentUpsert {
	u.Set(document.FieldDepth1, v)
	return u
}

// UpdateDepth1 sets the "depth1" field to the value that was provided on create.
func (u *DocumentUpsert) UpdateDepth1() *DocumentUpsert {
	u.SetExcluded(document.FieldDepth1)
	return u
}

// SetDepth2 sets the "depth2" field.
func (u *DocumentUpsert) SetDepth2(v string) *DocumentUpsert {
	u.Set(document.FieldDepth2, v)
	return u
}

// UpdateDepth2 sets the "depth2" field to the value that was provided on create.
func (u *DocumentUpsert) UpdateDepth2() *DocumentUpsert {
	u.SetExcluded(document.FieldDepth2)
	return u
}

// SetTitle sets the "title" field.
func (u *DocumentUpsert) SetTitle(v string) *DocumentUpsert {
	u.Set(document.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *DocumentUpsert) UpdateTitle() *DocumentUpsert {
	u.SetExcluded(document.FieldTitle)
	return u
}

// SetContent sets the "content" field.
func (u *DocumentUpsert) SetContent(v string) *DocumentUpsert {
	u.Set(document.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *DocumentUpsert) UpdateContent() *DocumentUpsert {
	u.SetExcluded(document.FieldContent)
	return u
}

// ClearContent clears the value of the "content" field.
func (u *DocumentUpsert) ClearContent() *DocumentUpsert {
	u.SetNull(document.FieldContent)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DocumentUpsert) SetUpdatedAt(v time.Time) *DocumentUpsert {
	u.Set(document.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DocumentUpsert) UpdateUpdatedAt() *DocumentUpsert {
	u.SetExcluded(document.FieldUpdatedAt)
	return u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *DocumentUpsert) SetCreatedByUserID(v uuid.UUID) *DocumentUpsert {
	u.Set(document.FieldCreatedByUserID, v)
	return u
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *DocumentUpsert) UpdateCreatedByUserID() *DocumentUpsert {
	u.SetExcluded(document.FieldCreatedByUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Document.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(document.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DocumentUpsertOne) UpdateNewValues() *DocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(document.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(document.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Document.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DocumentUpsertOne) Ignore() *DocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DocumentUpsertOne) DoNothing() *DocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DocumentCreate.OnConflict
// documentation for more info.
func (u *DocumentUpsertOne) Update(set func(*DocumentUpsert)) *DocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DocumentUpsert{UpdateSet: update})
	}))
	return u
}

// SetYear sets the "year" field.
func (u *DocumentUpsertOne) SetYear(v int) *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.SetYear(v)
	})
}

// AddYear adds v to the "year" field.
func (u *DocumentUpsertOne) AddYear(v int) *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.AddYear(v)
	})
}

// UpdateYear sets the "year" field to the value that was provided on create.
func (u *DocumentUpsertOne) UpdateYear() *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.UpdateYear()
	})
}

// SetDepth1 sets the "depth1" field.
func (u *DocumentUpsertOne) SetDepth1(v string) *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.SetDepth1(v)
	})
}

// UpdateDepth1 sets the "depth1" field to the value that was provided on create.
func (u *DocumentUpsertOne) UpdateDepth1() *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.UpdateDepth1()
	})
}

// SetDepth2 sets the "depth2" field.
func (u *DocumentUpsertOne) SetDepth2(v string) *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.SetDepth2(v)
	})
}

// UpdateDepth2 sets the "depth2" field to the value that was provided on create.
func (u *DocumentUpsertOne) UpdateDepth2() *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.UpdateDepth2()
	})
}

// SetTitle sets the "title" field.
func (u *DocumentUpsertOne) SetTitle(v string) *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *DocumentUpsertOne) UpdateTitle() *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *DocumentUpsertOne) SetContent(v string) *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *DocumentUpsertOne) UpdateContent() *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *DocumentUpsertOne) ClearContent() *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.ClearContent()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DocumentUpsertOne) SetUpdatedAt(v time.Time) *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DocumentUpsertOne) UpdateUpdatedAt() *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *DocumentUpsertOne) SetCreatedByUserID(v uuid.UUID) *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.SetCreatedByUserID(v)
	})
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *DocumentUpsertOne) UpdateCreatedByUserID() *DocumentUpsertOne {
	return u.Update(func(s *DocumentUpsert) {
		s.UpdateCreatedByUserID()
	})
}

// Exec executes the query.
func (u *DocumentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DocumentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DocumentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DocumentUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DocumentUpsertOne.ID is not supported by MySQL driver. Use DocumentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DocumentUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DocumentCreateBulk is the builder for creating many Document entities in bulk.
type DocumentCreateBulk struct {
	config
	err      error
	builders []*DocumentCreate
	conflict []sql.ConflictOption
}

// Save creates the Document entities in the database.
func (_c *DocumentCreateBulk) Save(ctx context.Context) ([]*Document, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Document, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DocumentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DocumentCreateBulk) SaveX(ctx context.Context) []*Document {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Document.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DocumentUpsert) {
//			SetYear(v+v).
//		}).
//		Exec(ctx)
func (_c *DocumentCreateBulk) OnConflict(opts ...sql.ConflictOption) *DocumentUpsertBulk {
	_c.conflict = opts
	return &DocumentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Document.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DocumentCreateBulk) OnConflictColumns(columns ...string) *DocumentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DocumentUpsertBulk{
		create: _c,
	}
}

// DocumentUpsertBulk is the builder for "upsert"-ing
// a bulk of Document nodes.
type DocumentUpsertBulk struct {
	create *DocumentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Document.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(document.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DocumentUpsertBulk) UpdateNewValues() *DocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(document.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(document.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Document.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DocumentUpsertBulk) Ignore() *DocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DocumentUpsertBulk) DoNothing() *DocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DocumentCreateBulk.OnConflict
// documentation for more info.
func (u *DocumentUpsertBulk) Update(set func(*DocumentUpsert)) *DocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DocumentUpsert{UpdateSet: update})
	}))
	return u
}

// SetYear sets the "year" field.
func (u *DocumentUpsertBulk) SetYear(v int) *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.SetYear(v)
	})
}

// AddYear adds v to the "year" field.
func (u *DocumentUpsertBulk) AddYear(v int) *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.AddYear(v)
	})
}

// UpdateYear sets the "year" field to the value that was provided on create.
func (u *DocumentUpsertBulk) UpdateYear() *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.UpdateYear()
	})
}

// SetDepth1 sets the "depth1" field.
func (u *DocumentUpsertBulk) SetDepth1(v string) *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.SetDepth1(v)
	})
}

// UpdateDepth1 sets the "depth1" field to the value that was provided on create.
func (u *DocumentUpsertBulk) UpdateDepth1() *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.UpdateDepth1()
	})
}

// SetDepth2 sets the "depth2" field.
func (u *DocumentUpsertBulk) SetDepth2(v string) *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.SetDepth2(v)
	})
}

// UpdateDepth2 sets the "depth2" field to the value that was provided on create.
func (u *DocumentUpsertBulk) UpdateDepth2() *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.UpdateDepth2()
	})
}

// SetTitle sets the "title" field.
func (u *DocumentUpsertBulk) SetTitle(v string) *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *DocumentUpsertBulk) UpdateTitle() *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *DocumentUpsertBulk) SetContent(v string) *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *DocumentUpsertBulk) UpdateContent() *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *DocumentUpsertBulk) ClearContent() *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.ClearContent()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DocumentUpsertBulk) SetUpdatedAt(v time.Time) *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DocumentUpsertBulk) UpdateUpdatedAt() *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *DocumentUpsertBulk) SetCreatedByUserID(v uuid.UUID) *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.SetCreatedByUserID(v)
	})
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *DocumentUpsertBulk) UpdateCreatedByUserID() *DocumentUpsertBulk {
	return u.Update(func(s *DocumentUpsert) {
		s.UpdateCreatedByUserID()
	})
}

// Exec executes the query.
func (u *DocumentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DocumentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DocumentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DocumentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
