// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"document-mdp/ent/document"
	"document-mdp/ent/documentalias"
	"document-mdp/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DocumentAliasUpdate is the builder for updating DocumentAlias entities.
type DocumentAliasUpdate struct {
	config
	hooks     []Hook
	mutation  *DocumentAliasMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DocumentAliasUpdate builder.
func (_u *DocumentAliasUpdate) Where(ps ...predicate.DocumentAlias) *DocumentAliasUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAlias sets the "alias" field.
func (_u *DocumentAliasUpdate) SetAlias(v string) *DocumentAliasUpdate {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *DocumentAliasUpdate) SetNillableAlias(v *string) *DocumentAliasUpdate {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetDocumentID sets the "document_id" field.
func (_u *DocumentAliasUpdate) SetDocumentID(v uuid.UUID) *DocumentAliasUpdate {
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *DocumentAliasUpdate) SetNillableDocumentID(v *uuid.UUID) *DocumentAliasUpdate {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// SetDocument sets the "document" edge to the Document entity.
func (_u *DocumentAliasUpdate) SetDocument(v *Document) *DocumentAliasUpdate {
	return _u.SetDocumentID(v.ID)
}

// Mutation returns the DocumentAliasMutation object of the builder.
func (_u *DocumentAliasUpdate) Mutation() *DocumentAliasMutation {
	return _u.mutation
}

// ClearDocument clears the "document" edge to the Document entity.
func (_u *DocumentAliasUpdate) ClearDocument() *DocumentAliasUpdate {
	_u.mutation.ClearDocument()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DocumentAliasUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentAliasUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DocumentAliasUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentAliasUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentAliasUpdate) check() error {
	if v, ok := _u.mutation.Alias(); ok {
		if err := documentalias.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "DocumentAlias.alias": %w`, err)}
		}
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentAlias.document"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DocumentAliasUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DocumentAliasUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DocumentAliasUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documentalias.Table, documentalias.Columns, sqlgraph.NewFieldSpec(documentalias.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(documentalias.FieldAlias, field.TypeString, value)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentalias.DocumentTable,
			Columns: []string{documentalias.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentalias.DocumentTable,
			Columns: []string{documentalias.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documentalias.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DocumentAliasUpdateOne is the builder for updating a single DocumentAlias entity.
type DocumentAliasUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DocumentAliasMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetAlias sets the "alias" field.
func (_u *DocumentAliasUpdateOne) SetAlias(v string) *DocumentAliasUpdateOne {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *DocumentAliasUpdateOne) SetNillableAlias(v *string) *DocumentAliasUpdateOne {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetDocumentID sets the "document_id" field.
func (_u *DocumentAliasUpdateOne) SetDocumentID(v uuid.UUID) *DocumentAliasUpdateOne {
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *DocumentAliasUpdateOne) SetNillableDocumentID(v *uuid.UUID) *DocumentAliasUpdateOne {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// SetDocument sets the "document" edge to the Document entity.
func (_u *DocumentAliasUpdateOne) SetDocument(v *Document) *DocumentAliasUpdateOne {
	return _u.SetDocumentID(v.ID)
}

// Mutation returns the DocumentAliasMutation object of the builder.
func (_u *DocumentAliasUpdateOne) Mutation() *DocumentAliasMutation {
	return _u.mutation
}

// ClearDocument clears the "document" edge to the Document entity.
func (_u *DocumentAliasUpdateOne) ClearDocument() *DocumentAliasUpdateOne {
	_u.mutation.ClearDocument()
	return _u
}

// Where appends a list predicates to the DocumentAliasUpdate builder.
func (_u *DocumentAliasUpdateOne) Where(ps ...predicate.DocumentAlias) *DocumentAliasUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DocumentAliasUpdateOne) Select(field string, fields ...string) *DocumentAliasUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DocumentAlias entity.
func (_u *DocumentAliasUpdateOne) Save(ctx context.Context) (*DocumentAlias, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentAliasUpdateOne) SaveX(ctx context.Context) *DocumentAlias {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DocumentAliasUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentAliasUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentAliasUpdateOne) check() error {
	if v, ok := _u.mutation.Alias(); ok {
		if err := documentalias.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "DocumentAlias.alias": %w`, err)}
		}
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentAlias.document"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DocumentAliasUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DocumentAliasUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DocumentAliasUpdateOne) sqlSave(ctx context.Context) (_node *DocumentAlias, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documentalias.Table, documentalias.Columns, sqlgraph.NewFieldSpec(documentalias.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DocumentAlias.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, documentalias.FieldID)
		for _, f := range fields {
			if !documentalias.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != documentalias.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(documentalias.FieldAlias, field.TypeString, value)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentalias.DocumentTable,
			Columns: []string{documentalias.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentalias.DocumentTable,
			Columns: []string{documentalias.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DocumentAlias{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documentalias.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
