// Code generated by ent, DO NOT EDIT.

package ent

import (
	"document-mdp/ent/document"
	"document-mdp/ent/documentacl"
	"document-mdp/ent/documentalias"
	"document-mdp/ent/documentembedding"
	"document-mdp/ent/group"
	"document-mdp/ent/refreshtoken"
	"document-mdp/ent/schema"
	"document-mdp/ent/user"
	"document-mdp/ent/usergroup"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	documentFields := schema.Document{}.Fields()
	_ = documentFields
	// documentDescDepth1 is the schema descriptor for depth1 field.
	documentDescDepth1 := documentFields[2].Descriptor()
	// document.Depth1Validator is a validator for the "depth1" field. It is called by the builders before save.
	document.Depth1Validator = func() func(string) error {
		validators := documentDescDepth1.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(depth1 string) error {
			for _, fn := range fns {
				if err := fn(depth1); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// documentDescDepth2 is the schema descriptor for depth2 field.
	documentDescDepth2 := documentFields[3].Descriptor()
	// document.Depth2Validator is a validator for the "depth2" field. It is called by the builders before save.
	document.Depth2Validator = func() func(string) error {
		validators := documentDescDepth2.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(depth2 string) error {
			for _, fn := range fns {
				if err := fn(depth2); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// documentDescTitle is the schema descriptor for title field.
	documentDescTitle := documentFields[4].Descriptor()
	// document.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	document.TitleValidator = func() func(string) error {
		validators := documentDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// documentDescCreatedAt is the schema descriptor for created_at field.
	documentDescCreatedAt := documentFields[6].Descriptor()
	// document.DefaultCreatedAt holds the default value on creation for the created_at field.
	document.DefaultCreatedAt = documentDescCreatedAt.Default.(func() time.Time)
	// documentDescUpdatedAt is the schema descriptor for updated_at field.
	documentDescUpdatedAt := documentFields[7].Descriptor()
	// document.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	document.DefaultUpdatedAt = documentDescUpdatedAt.Default.(func() time.Time)
	// document.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	document.UpdateDefaultUpdatedAt = documentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// documentDescID is the schema descriptor for id field.
	documentDescID := documentFields[0].Descriptor()
	// document.DefaultID holds the default value on creation for the id field.
	document.DefaultID = documentDescID.Default.(func() uuid.UUID)
	documentaclFields := schema.DocumentACL{}.Fields()
	_ = documentaclFields
	// documentaclDescCreatedAt is the schema descriptor for created_at field.
	documentaclDescCreatedAt := documentaclFields[4].Descriptor()
	// documentacl.DefaultCreatedAt holds the default value on creation for the created_at field.
	documentacl.DefaultCreatedAt = documentaclDescCreatedAt.Default.(func() time.Time)
	// documentaclDescUpdatedAt is the schema descriptor for updated_at field.
	documentaclDescUpdatedAt := documentaclFields[5].Descriptor()
	// documentacl.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	documentacl.DefaultUpdatedAt = documentaclDescUpdatedAt.Default.(func() time.Time)
	// documentacl.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	documentacl.UpdateDefaultUpdatedAt = documentaclDescUpdatedAt.UpdateDefault.(func() time.Time)
	// documentaclDescID is the schema descriptor for id field.
	documentaclDescID := documentaclFields[0].Descriptor()
	// documentacl.DefaultID holds the default value on creation for the id field.
	documentacl.DefaultID = documentaclDescID.Default.(func() uuid.UUID)
	documentaliasFields := schema.DocumentAlias{}.Fields()
	_ = documentaliasFields
	// documentaliasDescAlias is the schema descriptor for alias field.
	documentaliasDescAlias := documentaliasFields[1].Descriptor()
	// documentalias.AliasValidator is a validator for the "alias" field. It is called by the builders before save.
	documentalias.AliasValidator = func() func(string) error {
		validators := documentaliasDescAlias.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(alias string) error {
			for _, fn := range fns {
				if err := fn(alias); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// documentaliasDescCreatedAt is the schema descriptor for created_at field.
	documentaliasDescCreatedAt := documentaliasFields[2].Descriptor()
	// documentalias.DefaultCreatedAt holds the default value on creation for the created_at field.
	documentalias.DefaultCreatedAt = documentaliasDescCreatedAt.Default.(func() time.Time)
	// documentaliasDescID is the schema descriptor for id field.
	documentaliasDescID := documentaliasFields[0].Descriptor()
	// documentalias.DefaultID holds the default value on creation for the id field.
	documentalias.DefaultID = documentaliasDescID.Default.(func() uuid.UUID)
	documentembeddingFields := schema.DocumentEmbedding{}.Fields()
	_ = documentembeddingFields
	// documentembeddingDescModel is the schema descriptor for model field.
	documentembeddingDescModel := documentembeddingFields[1].Descriptor()
	// documentembedding.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	documentembedding.ModelValidator = func() func(string) error {
		validators := documentembeddingDescModel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(model string) error {
			for _, fn := range fns {
				if err := fn(model); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// documentembeddingDescCreatedAt is the schema descriptor for created_at field.
	documentembeddingDescCreatedAt := documentembeddingFields[4].Descriptor()
	// documentembedding.DefaultCreatedAt holds the default value on creation for the created_at field.
	documentembedding.DefaultCreatedAt = documentembeddingDescCreatedAt.Default.(func() time.Time)
	// documentembeddingDescID is the schema descriptor for id field.
	documentembeddingDescID := documentembeddingFields[0].Descriptor()
	// documentembedding.DefaultID holds the default value on creation for the id field.
	documentembedding.DefaultID = documentembeddingDescID.Default.(func() uuid.UUID)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[1].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = func() func(string) error {
		validators := groupDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupFields[2].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	// groupDescUpdatedAt is the schema descriptor for updated_at field.
	groupDescUpdatedAt := groupFields[3].Descriptor()
	// group.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	group.DefaultUpdatedAt = groupDescUpdatedAt.Default.(func() time.Time)
	// group.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	group.UpdateDefaultUpdatedAt = groupDescUpdatedAt.UpdateDefault.(func() time.Time)
	// groupDescID is the schema descriptor for id field.
	groupDescID := groupFields[0].Descriptor()
	// group.DefaultID holds the default value on creation for the id field.
	group.DefaultID = groupDescID.Default.(func() uuid.UUID)
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescTokenHash is the schema descriptor for token_hash field.
	refreshtokenDescTokenHash := refreshtokenFields[2].Descriptor()
	// refreshtoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	refreshtoken.TokenHashValidator = refreshtokenDescTokenHash.Validators[0].(func(string) error)
	// refreshtokenDescUserAgent is the schema descriptor for user_agent field.
	refreshtokenDescUserAgent := refreshtokenFields[5].Descriptor()
	// refreshtoken.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	refreshtoken.UserAgentValidator = refreshtokenDescUserAgent.Validators[0].(func(string) error)
	// refreshtokenDescIP is the schema descriptor for ip field.
	refreshtokenDescIP := refreshtokenFields[6].Descriptor()
	// refreshtoken.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	refreshtoken.IPValidator = refreshtokenDescIP.Validators[0].(func(string) error)
	// refreshtokenDescCreatedAt is the schema descriptor for created_at field.
	refreshtokenDescCreatedAt := refreshtokenFields[7].Descriptor()
	// refreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshtoken.DefaultCreatedAt = refreshtokenDescCreatedAt.Default.(func() time.Time)
	// refreshtokenDescID is the schema descriptor for id field.
	refreshtokenDescID := refreshtokenFields[0].Descriptor()
	// refreshtoken.DefaultID holds the default value on creation for the id field.
	refreshtoken.DefaultID = refreshtokenDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[3].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	usergroupFields := schema.UserGroup{}.Fields()
	_ = usergroupFields
	// usergroupDescCreatedAt is the schema descriptor for created_at field.
	usergroupDescCreatedAt := usergroupFields[1].Descriptor()
	// usergroup.DefaultCreatedAt holds the default value on creation for the created_at field.
	usergroup.DefaultCreatedAt = usergroupDescCreatedAt.Default.(func() time.Time)
	// usergroupDescID is the schema descriptor for id field.
	usergroupDescID := usergroupFields[0].Descriptor()
	// usergroup.DefaultID holds the default value on creation for the id field.
	usergroup.DefaultID = usergroupDescID.Default.(func() uuid.UUID)
}
