// Code generated by ent, DO NOT EDIT.

package documentembedding

import (
	"document-mdp/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldLTE(FieldID, id))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldEQ(FieldModel, v))
}

// Dims applies equality check predicate on the "dims" field. It's identical to DimsEQ.
func Dims(v int) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldEQ(FieldDims, v))
}

// Embedding applies equality check predicate on the "embedding" field. It's identical to EmbeddingEQ.
func Embedding(v pgvector.Vector) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldEQ(FieldEmbedding, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldEQ(FieldCreatedAt, v))
}

// DocumentID applies equality check predicate on the "document_id" field. It's identical to DocumentIDEQ.
func DocumentID(v uuid.UUID) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldEQ(FieldDocumentID, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldContainsFold(FieldModel, v))
}

// DimsEQ applies the EQ predicate on the "dims" field.
func DimsEQ(v int) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldEQ(FieldDims, v))
}

// DimsNEQ applies the NEQ predicate on the "dims" field.
func DimsNEQ(v int) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldNEQ(FieldDims, v))
}

// DimsIn applies the In predicate on the "dims" field.
func DimsIn(vs ...int) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldIn(FieldDims, vs...))
}

// DimsNotIn applies the NotIn predicate on the "dims" field.
func DimsNotIn(vs ...int) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldNotIn(FieldDims, vs...))
}

// DimsGT applies the GT predicate on the "dims" field.
func DimsGT(v int) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldGT(FieldDims, v))
}

// DimsGTE applies the GTE predicate on the "dims" field.
func DimsGTE(v int) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldGTE(FieldDims, v))
}

// DimsLT applies the LT predicate on the "dims" field.
func DimsLT(v int) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldLT(FieldDims, v))
}

// DimsLTE applies the LTE predicate on the "dims" field.
func DimsLTE(v int) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldLTE(FieldDims, v))
}

// EmbeddingEQ applies the EQ predicate on the "embedding" field.
func EmbeddingEQ(v pgvector.Vector) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldEQ(FieldEmbedding, v))
}

// EmbeddingNEQ applies the NEQ predicate on the "embedding" field.
func EmbeddingNEQ(v pgvector.Vector) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldNEQ(FieldEmbedding, v))
}

// EmbeddingIn applies the In predicate on the "embedding" field.
func EmbeddingIn(vs ...pgvector.Vector) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldIn(FieldEmbedding, vs...))
}

// EmbeddingNotIn applies the NotIn predicate on the "embedding" field.
func EmbeddingNotIn(vs ...pgvector.Vector) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldNotIn(FieldEmbedding, vs...))
}

// EmbeddingGT applies the GT predicate on the "embedding" field.
func EmbeddingGT(v pgvector.Vector) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldGT(FieldEmbedding, v))
}

// EmbeddingGTE applies the GTE predicate on the "embedding" field.
func EmbeddingGTE(v pgvector.Vector) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldGTE(FieldEmbedding, v))
}

// EmbeddingLT applies the LT predicate on the "embedding" field.
func EmbeddingLT(v pgvector.Vector) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldLT(FieldEmbedding, v))
}

// EmbeddingLTE applies the LTE predicate on the "embedding" field.
func EmbeddingLTE(v pgvector.Vector) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldLTE(FieldEmbedding, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldLTE(FieldCreatedAt, v))
}

// DocumentIDEQ applies the EQ predicate on the "document_id" field.
func DocumentIDEQ(v uuid.UUID) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldEQ(FieldDocumentID, v))
}

// DocumentIDNEQ applies the NEQ predicate on the "document_id" field.
func DocumentIDNEQ(v uuid.UUID) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldNEQ(FieldDocumentID, v))
}

// DocumentIDIn applies the In predicate on the "document_id" field.
func DocumentIDIn(vs ...uuid.UUID) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldIn(FieldDocumentID, vs...))
}

// DocumentIDNotIn applies the NotIn predicate on the "document_id" field.
func DocumentIDNotIn(vs ...uuid.UUID) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.FieldNotIn(FieldDocumentID, vs...))
}

// HasDocument applies the HasEdge predicate on the "document" edge.
func HasDocument() predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, DocumentTable, DocumentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDocumentWith applies the HasEdge predicate on the "document" edge with a given conditions (other predicates).
func HasDocumentWith(preds ...predicate.Document) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(func(s *sql.Selector) {
		step := newDocumentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DocumentEmbedding) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DocumentEmbedding) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DocumentEmbedding) predicate.DocumentEmbedding {
	return predicate.DocumentEmbedding(sql.NotPredicates(p))
}
