// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Document is the predicate function for document builders.
type Document func(*sql.Selector)

// DocumentACL is the predicate function for documentacl builders.
type DocumentACL func(*sql.Selector)

// DocumentAlias is the predicate function for documentalias builders.
type DocumentAlias func(*sql.Selector)

// DocumentEmbedding is the predicate function for documentembedding builders.
type DocumentEmbedding func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// RefreshToken is the predicate function for refreshtoken builders.
type RefreshToken func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserGroup is the predicate function for usergroup builders.
type UserGroup func(*sql.Selector)
